### ISSUE TITLE
Développement d'un affichage sous forme de clustering attributaire

### ISSUE THREAD

**Issue by pigma** [mviewer/mviewer#265]
Bonjour,

Pour information, un mode d'affichage de données vecteurs sous forme de cluster "Attributaire" est en cours de développement avec la société JDEV.

Ce mode d'affichage doit permettre de regrouper des données sous forme de cluster non pas en fonction d'une distance, mais d'un même attribut.

Ces développements se font dans le cadre d'un partenariat entre le GIP Littoral et le GIP ATGeRi avec la mise en place d'une base de données plages de Nouvelle-Aquitaine.

Bonne journée,

**Comment by Gaetanbrl** [comment]
@spelhate je pense proposer une démo dans pas très longtemps.

**Comment by lecault** [comment]
A clore ?

**Comment by Gaetanbrl** [comment]
A faire un jour... 🙈

**Comment by Gaetanbrl** [comment]
je clos, concerne explications dans #488
