### ISSUE TITLE
Module d'impression plus riche que la simple copie d'écran

### ISSUE THREAD

**Issue by bchartier** [mviewer/mviewer#467]
**Description détaillée / Detailed description**

Pouvoir imprimer la carte avec un peu plus de choses que le simple export PNG (légende, échelle, titre, date).

**Informations complémentaires / Additional context**

x

**Comment by bchartier** [comment]
Au cours de la dernière réunion du comité de pilotage il a été évoqué plusieurs possibilités déjà plus ou moins expérimentées mais non intégrées à mviewer pour l'instant :
- développement en PHP (donc exécuté sur un serveur) appelé par mviewer et qui permettrait à l'utilisateur de définir sa mise en page, d'intégrer des contenus personnalisés (libellés dans des boites de texte par exemple, la légende des couches...) et de produire le document final (expérimenté par @spelhate)
- développement Javascript exécuté par le navigateur de l'utilisateur qui réaliserait la même chose que le dev PHP évoqué juste avant (expérimenté par @Gaetanbrl)
- existence de bibliothèques Javascript qui permettent d'écrire des fichiers PDF. À voir si cela peut être utilisé par les navigateurs ou côté serveur avec Node par exemple.

En suivant ces pistes on aurait toujours une qualité d'impression de la carte qui serait celle d'une copie d'écran (mais avec un titre, une description, une légende...).

**Comment by bchartier** [comment]
@vfabry : n'hésite pas à compléter ou commenter par rapport à ton besoin. Visiblement il y a des gens qui sont intéressés par le développement de cette fonction.

**Comment by Gaetanbrl** [comment]
> existence de bibliothèques Javascript qui permettent d'écrire des fichiers PDF. À voir si cela peut être utilisé par les navigateurs ou côté serveur avec Node par exemple.

Je complète ce point : 

Si on utilise une page web dédiée, le navigateur peut parfaitement générer lui-même le PDF via l'impression standard Chrome, FF, autre.

**Comment by Gaetanbrl** [comment]
> En suivant ces pistes on aurait toujours une qualité d'impression de la carte qui serait celle d'une copie d'écran (mais avec un titre, une description, une légende...).

Testé en mode web : possibilité de modifier de façon dynamique les titres, ajouter du texte, la police, etc.
