### ISSUE TITLE
Page d'erreur - afficher le lien complet

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewer#540]
# Description

Lorsqu'on a une page d'erreur pendant la réalisation d'une application ou pendant des développements, on doit re saisir l'ensemble de l'URL.

Nous proposons avec @Agath21 d'avoir un lien complet dans cette page avec l'URL qui a été saisie et qui retourne une erreur.

Nous n'aurions qu'à la copier et modifier l'URL, ce serait de plus assez simple de voir l'erreur dans le cas où ce serait le mauvais répertoire qui serait appelé dans le Mviewer.

C'est une petite évolution mais qui nous sera plus confortable pendant des développements je pense.

**Comment by lecault** [comment]
tant que l'on y est, il y a t'il la possibilité d'ajouter le détail cf cette issue : #466

**Comment by lecault** [comment]
clos pr #878
