### ISSUE TITLE
Passer en option la redirection page d'erreur 

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewer#559]
Mviewer v3.7

# Description

Lorsqu'on a une erreur dans le XML, on a la page "Oops !" mais nous n'avons pas plus d'infos sur l'erreur... ni dans la console ni sur l'écran. Ce qui ne simplifie pas le debug.

Je propose de mettre au moins en option la redirection par défaut... ou alors j'ai oublié une option déjà existante ?

https://github.com/geobretagne/mviewer/blob/d862151406effda754999aed570d71fdcf923889/index.html#L579-L581

**Comment by Gaetanbrl** [comment]
> tu proposes d'ajouter une option permettant de choisir le type d'affichage de l'erreur ?

Quelque chose comme ca en effet, je n'ai pas réfléchi à la solution encore, mais sinon il faut aller dans l'index.html et commenter la section qui réalise la redirection.

**Comment by lecault** [comment]
clos pr #878
