### ISSUE TITLE
Raccourci # - perte du paramètre lors des changements d'affichage de couches

### ISSUE THREAD

**Issue by pbarille** [mviewer/mviewer#579]
Bonjour, 

**Description du bug / Describe the bug**

Nous apprécions beaucoup la fonction de raccourci présente dans le mviewer (mviewer/#mon_appli) mais nous avons remarqué que lorsque l'utilisateur change les couches affichées, le "monappli" présent après le # disparait. Ce qui pose problème lorsque l'utilisateur rafraîchit la page par exemple.

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page mviewer/#default
2. Afficher une couche non présente par défaut sur la page

**Comportement attendu / Exptected behavior**

Conserver le mot default après le #

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: Windows / Linux
 - Navigateur / browser: Chrome, edge, firefox

**Informations complémentaires / Additional context**

Mviewer 3.6.1

Merci !

**Comment by lecault** [comment]
Je n'avais jamais fait attention à cette fonctionnalité que nous n'utilisons pas ayant un répertoire par application.
Effectivement, il y a un petit dysfonctionnement.

**Comment by Gaetanbrl** [comment]
@lecault next minor release.

**Comment by lecault** [comment]
Avec @spelhate nous avons regardé suite à nos dev en cours sur mviewerstudio.
En fait, c'est l'arborescence qui a évolué.
Il faut stocker au même niveau ton xml et ton répertoire avec le même nom.
Exemple à la région avec un territoire.xml et au même niveau un dossier territoire (et non le xml dans le dossier).

https://kartenn.region-bretagne.fr/kartoviz/#region/territoire
