### ISSUE TITLE
metadata-csw : format de la date

### ISSUE THREAD

**Issue by vfabry** [mviewer/mviewer#615]
**Description / Describe**

Si on renseigne le paramètre metadata-csw et qu'une date de création a été renseignée dans la métadonnée, alors cette date apparait à côté de l'attribution, au format YYYY-MM-DD.

Ce serait compliqué de l'afficher en DD-MM-YYYY ?

Vincent

**Comment by lecault** [comment]
Je dirai que c'est ici où il faudrait faire la modif : 
                    var modifiedDate = $(result).find("dct\\:modified, modified").text() || $(result).find("dct\\:created, created").text();
                    _overLayers[this.layer].modifiedDate = modifiedDate;

N'étant pas chaud pour ajouter un énième paramètre, je m'interroge si cela vaut le coup de changer le format en dur ?
Je pense à l'utilisateur hors France.

**Comment by vfabry** [comment]
Alors moi je me pose la pertinence même de l'affichage de cette date. Je m'en passerai bien, quelque soit le format. J'ai l'impression que ça n'a pas toujours existé, ça avait été discuté quelque part ?

**Comment by Gaetanbrl** [comment]
@spelhate @lecault @smevel ?

**Comment by lecault** [comment]
J'avoue ne pas y faire attention du tout et effectivement ce n'est pas indispensable.

La source est ici : https://github.com/geobretagne/mviewer/issues/362

**Comment by spelhate** [comment]
> Alors moi je me pose la pertinence même de l'affichage de cette date. Je m'en passerai bien, quelque soit le format. J'ai l'impression que ça n'a pas toujours existé, ça avait été discuté quelque part ?

C'était il me semble une demande du département de Haute Loire et un dev réalisé par C2C.

**Comment by vfabry** [comment]
J'ai l'impression que sur les releases récentes, la date n'est plus affichée, ce qui ma va très bien. Je propose de fermer ici.

**Comment by Gaetanbrl** [comment]
ok je clos merci
