### ISSUE TITLE
Import thème externe : changement du nom

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#616]
**Description / Describe**

J'aimerai avoir la possibilité de changer le nom d'un thème externe que l'on importe dans un mviewer.

**Description détaillée / Detailed description**

Voici un exemple d'import d'un thème externe : 

```
    <theme id="economie" url="https://kartenn.region-bretagne.fr/territoires/apps/default.xml" name="Données de contexte" collapsed="true" icon="false"> 
    </theme> 

```
Actuellement, le paramètre name n'est pas pris en compte : dans le mviewer le thème va s'appeler forcément comme dans le mviewer d'origine. Exemple ici Economie et emploi.

**Informations complémentaires / Additional context**

Je ne sais pas si c'est faisable facilement, merci pour les réponses.

**Comment by spelhate** [comment]
En lien avec cette demande, une nouvelle évolution côté Studio permet de définir la visibilité  d'une **thématique importée**.

La logique est la suivante (https://github.com/mviewer/mviewerstudio/issues/159)

>Pour gérer l'affichage des couches au sein d'une thématique externe lors du démarrage de l'application, création d'un nouveau paramètre layersvisibility spécifique aux thématiques externes avec les valeurs possibles :

>default : Afficher les données par défaut comme défini dans l'application source
all : Afficher toutes les données de la thématique externe
none : Aucune donnée n'est affichée

>Exemple :
```xml
<theme id="education" url="https://kartenn.region-bretagne.fr/territoires/apps/default.xml" name="Education et formation" collapsed="true" icon="false" layersvisibility="none"> 
</theme>

```

Il est nécessaire de développer ce nouveau paramétrage côté mviewer.
