### ISSUE TITLE
OGC API feature

### ISSUE THREAD

**Issue by vfabry** [mviewer/mviewer#617]
**Description / Describe**

Mviewer pourrait consommer des données venant de l'OGC API feature ?

**Informations complémentaires / Additional context**

Notre (geo2france) geoserver est capable d'en fournir, si des gens veulent tester...
Exemple avec la couche des sections cadastrales 2020 : **pci:geo_section_2020**

Accès aux données en geojson : https://dev.geo2france.fr/geoserver/ogc/features/collections/pci:geo_section_2020/items?f=application%2Fgeo%2Bjson&limit=50

**Comment by vfabry** [comment]
un custom layer "classique" suffirait, en fait !?

**Comment by Gaetanbrl** [comment]
mais @vfabry quels sont services que tu vises ? Seulement la consommation des données d'une API Feature ?

**Comment by vfabry** [comment]
> mais @vfabry quels sont services que tu vises ? Seulement la consommation des données d'une API Feature ?

pour l'instant oui. l'idée c'est de comparer les perfs avec un WFS classique sur des couches avec beaucoup d'objets.

**Comment by dds2010** [comment]
Intéressant comme test. Je n'ai pas bien compris ce qu'apportait l'OGC API feature par rapport à WFS 2.0. 
A priori je dirais que ça change le protocole, la manière de faire les requêtes mais je ne pense pas que cela ait d'impacts sur les fonctionnalités ou les performances.

**Comment by Gaetanbrl** [comment]
> Je n'ai pas bien compris ce qu'apportait l'OGC API feature par rapport à WFS 2.0

Ca permettra d'avoir des lecture / écriture via du REST OGC + classiques. C'est notamment intéressant pour la partie édition / update sans avoir à faire du WFS-T.

**Comment by dds2010** [comment]
ok merci, effectivement ça va simplifier les échanges.

**Comment by spelhate** [comment]
> **Description / Describe**
> 
> Mviewer pourrait consommer des données venant de l'OGC API feature ?
> 
> **Informations complémentaires / Additional context**
> 
> Notre (geo2france) geoserver est capable d'en fournir, si des gens veulent tester... Exemple avec la couche des sections cadastrales 2020 : **pci:geo_section_2020**
> 
> Accès aux données en geojson : https://dev.geo2france.fr/geoserver/ogc/features/collections/pci:geo_section_2020/items?f=application%2Fgeo%2Bjson&limit=50

J'ai une erreur sur le flux : 
```json
{"code":"NoApplicableCode","description":"org.springframework.transaction.TransactionSystemException: Could not roll back JPA transaction; nested exception is javax.persistence.PersistenceException: unexpected error when rollbacking\nCould not roll back JPA transaction; nested exception is javax.persistence.PersistenceException: unexpected error when rollbacking\nunexpected error when rollbacking\nCannot release connection\nAlready closed."}

**Comment by spelhate** [comment]
Merci @Gaetanbrl 
Le flux fonctionne maintenant aussi chez moi en copiant l'URL dans le navigateur, ce qui n'était pas le cas ce matin.

**Comment by vfabry** [comment]
J'ai fait un test sur ce mviewer : https://dev.geo2france.fr/mviewer/?config=apps/test_api_ogc_feature.xml# avec
* la couche des sections cadastrales en wfs
* la couche des sections cadastrales en API OGC (limiée à 5000 objets)
Les perfs sont pas extra, mais c'est à relativiser, car le test est hébérgé (mviewer + geoserver) sur notre plateforme dév, qui n'est pas dimensionnée pour ça.

**Comment by Gaetanbrl** [comment]
Merci du test @vfabry !

> la couche des sections cadastrales en wfs
> Les perfs sont pas extra

Il faut penser que le vectoriel + appli web c'est jamais extra quand on commence à avoir de la volumétrie. Le navigateur doit faire la requête, stocker les objets. Ca doit être pareil avec OGC API car on doit récupérer un JSON au bout comme le WFS.

On a en premier le soucis du débit de la connexion, et ensuite le soucis de traitement / affichage. Même avec un bon PC ca rame par exemple avec un JSON des contours détaillées des départements d'une région.

Je pense que l'essentiel étant que ca marche avec un type OGC API, le reste c'est à l'utilisateur de savoir si c'est mieux d'utiliser un flux type JSON ou un WMS + prévu pour des données en nombre.

**Comment by vfabry** [comment]
Je propose de fermer ici.

**Comment by Gaetanbrl** [comment]
ok je clos merci
