### ISSUE TITLE
[Evolution] Module d'impression papier

### ISSUE THREAD

**Issue by jerbou** [mviewer/mviewer#620]
**Description / Describe**
Nos utilisateurs ont émis le souhait de disposer d'un module d'impression papier (générer un PDF avec qq possibilités activables via une interface "simple" : 

- possibilité à l'utilisateur de saisir un titre
- possibilité d'ajouter le barreau d'échelle
- posssilibté d'ajouter la légende (le panneau légende)
- permet le choix de format feuille : A4, A3 et orientation portrait ou paysage
- ajouter un tag : date d'impression
- Avec prévisaulisation, et possibilité interactive à l'utilisateur de placer "chaque encart"

**Description détaillée / Detailed description**
L'évolution est ambitieuse mais répondrai à un besoin qui demeure important.
Est-ce que la communauté a des prerequis à suivre pour faire développer l’évolution et "faire le pull request" dans les meilleurs conditions ?
Quelle est le meilleur "tempo" ? développer sur une prochaine version, ou est-ce que l'on peut développer sur la dernière stable (3.7) ?

**Informations complémentaires / Additional context**
Nous avons identifié le presta'.

Toutes informations complémentaires que vous jugez utiles.

**Comment by Gaetanbrl** [comment]
> Est-ce que la communauté a des prerequis à suivre pour faire développer l’évolution et "faire le pull request" dans les meilleurs conditions ?

1. Lire la doc et les recommandations
2. Ouvrir une issue qui décrit le plus possible ce qui est prévu techniquement ET fonctionnellement pour qu'on comprenne bien et qu'on puisse bien se projeter pour rebondir sur des points positifs ou à maturer (avec des captures / maquettes ce serait le top)
3. Soit lancer les développements si la solution pressenti est la bonne (avec ou sans le retour communauté - à vous de voir, la PR sera là pour l'analyse de toute façon)
4. Faire la PR
5. Etre prêt à faire les modifications demandées par la communauté en tenant compte du temps à passer 

J'insiste sur le dernier point - le temps à passer après la création de la PR peut être sous estimé ou totalement inconnu si on est pas habitué du fonctionnement open source / communauté.

**Comment by jerbou** [comment]
Merci à vous deux pour les réponses rapides.

@spelhate : on rediscutera de ton RETEX, pour affiner les spec' sur le module impression
@Gaetanbrl : merci pour la méthode, je transmettrai. On reparlera d'un planning, timing partagé en PSC, si vous voulez.

De mon côté, l'échange peut être clos avec vos réponses.
Est-ce que je fais un ticket spécifique : dev' complémentaire module impression ?

A plus,

**Comment by jerbou** [comment]
je prefere garder ce ticket là et j'ai fait une proposition de renommage

**Comment by Gaetanbrl** [comment]
ref #6

**Comment by jerbou** [comment]
Est- ce qu'il serait possible d'ajouter un bloc avec le QR code généré par Mviewer ?

Cela permettrait à la personne qui consulter le PDF généré de retrouver trés facilement l'interactivité avec la carte interactive.

D'avance Merci,

**Comment by Gaetanbrl** [comment]
**Les éléments qui suivent sont des propositions d'organisation.**

### Projet 

J'ai créé un projet pour le suivi des issues de cette thématique :
https://github.com/mviewer/mviewer/projects/9

### Découpage des issues

Chacune de ces issues devra être créées dans ce dépôt principal mviewer afin que avancements, tests et échanges puissent rester visibles et disponibles par la communauté.

Les issues suivantes sont à créer (cette liste est à compléter si besoin) :

- Accès au plugin
- Interface initiale
- Configuration du module d’impression
- Personnalisation du gabarit sélectionné (redimensionnement des blocs, suppressions des blocs...)
- Sélection du gabarit (modèle ou personnalisation)

> Si la communauté le souhaite, ces issues peuvent être ouvertes dans un fork pour éviter de créer trop d'issue dans le dépôt principal mviewer. En l'absence de réaction de la communauté, les issues seront ouvertes dans le dépôt principal /mviewer de l'organisation Github mviewer.

### Documentation

La documentation est une tâche à réaliser au fil de l'eau pour chaque issue (si nécessaire).

### Processus de validation avant / après réalisation

Chaque issue doit avoir un retour (validation) avant démarrage de la part de la communauté ou du contributeur (@jerbou, autres ?).

Chaque issue doit avoir une validation (tests) avant d'être close via le processus de contribution défini dans la documentation mviewer.


**N'hésitez-pas à rebondir sur ces différents points.**

**Comment by jerbou** [comment]
Je valide les spécifications du module d’impression.

Nous avons identifié une "limite fonctionnelle", comment faire pour le retour d'information. (différence fonctionnelle entre l'optimisation d'impression qui peut le prendre en compte à minima mais pas le plugin).

Le retour d'une fiche d'information  (getfeatureinfo) ne fait pas partie du plugin, qui sert à afficher, imprimer les affichages thématiques et couches présentes à l'écran, avec la personnalisation pour chaque bloc dans les deux gabarits proposé.

Il est retenu qu'un concepteur de carte mviewer pourra également "customiser" ses propres gabarits en éditant les fichiers de configuration présent dans le plugin.

N’hésitez pas à compléter si ma reformulation est maladroite.

Merci,
