### ISSUE TITLE
Ajout SensorThings au coeur de Mviewer

### ISSUE THREAD

**Issue by pierrejego** [mviewer/mviewer#627]
**Description / Describe**

SensorThings a un standard OGC https://www.ogc.org/standards/sensorthings
Ce standard permet d'avoir une interopérabilité avec tous les données de capteurs. 
L'Agrocampus travaille sur le sujet et serait intéresser par ajouter le type SensorThings dans mviewer au même titre que le WMS ou WFS

**Description détaillée / Detailed description**

L'idée serait de permettre via le fichier de configuration du mviewer de créer un thème/layer Sensorthings pour faciliter la mise en place rapide d'outils de visualisation de la données

**Informations complémentaires / Additional context**

Il peut y avoir des très nombreux capteurs et données de capteurs, l'idée de cette première implémentation est de réaliser les bons steps d'appel pour afficher les données, sans rentrer pour l'instant dans la complexité de lire une montagne de données. 

Cette première implémentation devra limité le nombre d'éléments reçu.

**Comment by bchartier** [comment]
Est-ce qu'on a des URL d'API implémentant SensorThings avec lesquelles on pourrait jouer ?

**Comment by Agath21** [comment]
@hsquividant est-ce que je peux partager le lien vers le démonstrateur SensorThings basé sur Mviewer et l'API geosas associée ?

**Comment by hsquividant** [comment]
@Agath21 et @bchartier, oui l'INRAE, le BRGM, IFREMER et proposent des API SensorThings en production :

- **https://api.geosas.fr/agri4cast/v1.0/**
Données météo journalières maillées (20 km) depuis 20 ans sur la Bretagne, bientôt étendues à la France

- **https://sensorthings-wq.brgm-rec.fr/FROST-Server/v1.0/** (certificat https en cours de renouvellement)
Qualité des eaux de surface en France

- **https://sensorthings.geomatys.com/examind/WS/sts/default/**
Données météo acquises sur des balises en mer

Du côté de l'INRAE, à minima 2 observatoires labellisés "long terme" devraient devraient proposés leur API SensorThings à l'automne. Lidée serait de proposer au sein d'un même visualiseur des données spatiales via flux WMS/WFS + SLD + Dataviz ET des données temporelles via flux SensorThings, un besoin à priori générique pour tous les observatoires de recherche.

**Comment by spelhate** [comment]
> Quelques exemples de requête utile pour le Mviewer :
> 
> _Thing : exemple une station de mesure Location : emplacement géographique des Things Datastream : regroupe les observations d'une même propriété (ex Température). Un Datastream est associé à une Thing._

Merci c'est très clair et ça aide à se projeter.

**Comment by Gaetanbrl** [comment]
Suite à une première présentation des premiers travaux au PSC : 

- Une contribution est bienvenu pour un nouveau type de couche
- La couche devra être intégrée comme une couche classique
- La sélection des datastream / Multidatastream sera insérée dans un nouveau control de couche :

https://github.com/geobretagne/mviewer/blob/master/js/templates.js#L169-L181

La branche qui servira à la contribution a été créée :

https://github.com/geobretagne/mviewer/tree/issue-627

**Comment by Gaetanbrl** [comment]
Je clos PR mergée. Je rajoute une issue sur le multidatastream qui n'a pas un comportement optimal.
