### ISSUE TITLE
Ajouter une couche WMS à la carte

### ISSUE THREAD

**Issue by vfabry** [mviewer/mviewer#629]
**Description / Describe**

Avoir un bouton dans l'interface (dans le panneau de gauche ?) qui permet à l'utilisateur final d'ajouter une couche WMS (non persistante) à la carte.

**Description détaillée / Detailed description**

On pourra paramétrer dans la config de l'extension un certain nombre de service WMS et CSW. L'utilisateur final pourra : 
-	Afficher des couches d’un service WMS,
-	Afficher des couches d’un service CSW,
-	Sélectionner une couche et ajouter dans la carte courante

**Informations complémentaires / Additional context**

- Traitement des spécificités Geoserver/QgisServer/Mapserver
- Ajout d’une couche WMS à partir de paramètres récupérés dans l’url => pour avoir un bouton « ouvrir dans Mviewer » depuis un catalogue externe.

Géo2France a confié ce développement à @dds2010 (neogeo technologie).

Vincent

**Comment by Gaetanbrl** [comment]
> A noter pour les prochaines issues et peut être à rajouter dans la doc @spelhate @lecault 

Juste un petit commentaire qui vaut pour tous les contributeurs et pas spécifiquement que pour cette contribution :

-------------

Il est plus que conseillé qu'une issue qui accompagne une évolution **décrive le comportement fonctionnel et technique envisagé**.

Par exemple, pour cette issue bien que le comportement proposé soit satisfaisant il aurait pu être préférable d'avoir une extension pour l'ajout d'un flux WMS. 

Pour rappel, en décrivant la solution prévue sans l'issue, une discussion peut avoir lieu afin d'aller dans la bonne direction lors de la réalisation de la PR. Cette bonne pratique évite d'avoir trop de surprise lors de la revue et que le contributeur ne dispose plus de temps pour faire les adaptations demandées par les reviewers...

**Globalement** : 

- Une PR n'est pas une contribution validée d'avance **en l'état**
- Une PR donne lieu à une phase de revue / échange qui peut demander du temps (voir encore plus de temps lorsque le comportement n'a pas été confirmé / compris par la communauté)

**Comment by dds2010** [comment]
Attention a ne pas décourager les contributions avec ce type de commentaire, nous avons essayé de faire au mieux et de suivre les consignes. On a fait une issue début juillet qui n a suscité aucun retours ou demandes de précisions. Nous avons fait la PR début septembre en essayant de decrire ce qui a été fait de manière à pouvoir réajuster le tir techniquement  sur la PR si besoin était. La encore peu de retours et de manière très décousue. Je ne jette pas la pierre, chacun a son planning et c est normal, mais ensuite faut pas aller chercher la petite bête...

**Comment by Gaetanbrl** [comment]
> Attention a ne pas décourager les contributions avec ce type de commentaire

Je m'excuse, ce n'est pas l'idée.

> nous avons essayé de faire au mieux et de suivre les consignes

L'idée du commentaire est de s'améliorer au fil des contributions. Je pense que ce point est manquant dans la documentation en plus du template de l'issue, ce n'est pas pour pointer du doigts cette issue uniquement.

C'est une demande qu'on a dans d'autres communautés open source, alors je trouvais ca adéquate qu'on l'applique dans le futur peut être pour gagner en réactivité, car c'est pas simple de voir le résultat final quand on est pas dans les échanges du besoin initial.

>  La encore peu de retours et de manière très décousue. Je ne jette pas la pierre, chacun a son planning et c est normal, mais ensuite faut pas aller chercher la petite bête...

Désolé pour ce manque de réactivité sur ta PR @dds2010, comme tu as vu en suivant l'activité mviewer lors de ta PR on a eu pas mal de PR à gérer en même temps et pas plus de ressource pour nous aider à les inspecter / tester. 
Tout renfort est pourtant le bienvenu pour nous aider dans les revues.
 
On essaiera de faire mieux la prochaine fois :) !

**Comment by lecault** [comment]
PR validée
