### ISSUE TITLE
Comportement fiche info

### ISSUE THREAD

**Issue by bdavid-rennesmetrpole** [mviewer/mviewer#632]
En mode simplifié et en mode ultra-simplifié, les fiches d'information des entités cliquées s'affichent dans des fenêtres modales.

Cependant il n'est possible de les ouvrir qu'en cliquant sur le titre.

L'idée est de compléter ces modales avec quelques ajouts:

- pouvoir plier/déplier la fiche d'info par un clic sur le cadre d'entête noir complet 
- avoir des icones +/- qui indiquent l'onglet plié ou déplié

![carto_capt](https://user-images.githubusercontent.com/85627821/180799951-f43a2505-9d8b-4778-a514-dd7e27cfd34b.png)

**Comment by Gaetanbrl** [comment]
Bonne idée, ca serait plus sympa avec les + ou - selon l'état.

**Comment by Gaetanbrl** [comment]
> Cependant il n'est possible de les ouvrir qu'en cliquant sur le titre.

Est-ce que la map serait syncro avec l'ouverture des infos de la feature ?

**Comment by smevel** [comment]
Comportement sous bootstrap 5
https://getbootstrap.com/docs/5.0/components/accordion/


De : bdavid ***@***.***>
Envoyé : lundi 25 juillet 2022 16:24
À : geobretagne/mviewer ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [geobretagne/mviewer] Comportement fiche info (Issue #632)


En mode simplifié et en mode ultra-simplifié, les fiches d'information des entités cliquées s'affichent dans des fenêtres modales.

Cependant il n'est possible de les ouvrir qu'en cliquant sur le titre.

L'idée est de compléter ces modales avec quelques ajouts:

  *   pouvoir plier/déplier la fiche d'info par un clic sur le cadre d'entête noir complet
  *   avoir des icones +/- qui indiquent l'onglet plié ou déplié

[carto_capt]<https://user-images.githubusercontent.com/85627821/180799951-f43a2505-9d8b-4778-a514-dd7e27cfd34b.png>

**Comment by Gaetanbrl** [comment]
Bootstrap 5 n'est pas compatible avec mviewer.
Mviewer utilise Bootstrap 3.3.6 pour le moment (des changements à venir) 

https://github.com/geobretagne/mviewer/tree/master/lib/bootstrap/3.3.6

**Comment by bdavid-rennesmetrpole** [comment]
> > Cependant il n'est possible de les ouvrir qu'en cliquant sur le titre.
> 
> Est-ce que la map serait syncro avec l'ouverture des infos de la feature ?

Je n'ai pas prévu de changer le fonctionnement de la carte, simplement l'ajout d'un + et - selon l'état et d'étendre la zone cliquable

**Comment by Gaetanbrl** [comment]
@bdavid-rennesmetrpole avez-vous une démo public quelque part ?

**Comment by bdavid-rennesmetrpole** [comment]
Bonjour,
voici une PR correspondant à l'évolution proposée
https://github.com/mviewer/mviewer/pull/743

**Comment by Gaetanbrl** [comment]
Bonjour,

Merci pour ces modifications.
Cependant pour une contribution, c'est l'évolution sur mviewer qui nous intéresse.
Je pense qu'il n'est pas utile de partager votre application dans apps mais plutôt d'appliquer votre modification à une démonstration déjà existante (ou de nous fournir le lien de test depuis un XML qui existe déjà).

Votre contribution devrait donc contenir les éléments suivant (si j'ai bien compris votre modifications) : 

- la modification css (`css/mviewer.css`)
- la modification du mst qui permet d'utiliser les accordéons (mode ouvert / fermé) (`js/templates.js`)

Ces modifications dites "dans le coeur" sont l'essentiel de votre contribution, car elles permettent d'améliorer l'existant.

Le process étant : 

1. on récupère vos modifications dans le coeur (uniquement celle du coeur)
2. on test avec une démo déjà existante en mode ultra
3. on valide ... ou on voit ensemble les ajustements :)


Je vous propose donc de supprimer dans cette PR @bdavid-rennesmetrpole les fichiers / répertoires que ne seront pas utilisés par la communauté, c'est à dire tous ce qui n'est `pas` dans `/js`, `/css`.

Si vous souhaitez partager une démo liée à votre évolution alors vous pouvez en partager une dans le répertoire (où NOM_DE_MA_DEMO est à personnaliser selon le nom que vous désirez) : 

/demo/NOM_DE_MA_DEMO
