### ISSUE TITLE
GetFeatureInfo - les requêtes Ajax appellent le proxy malgré useproxy = false

### ISSUE THREAD

**Issue by benjaminh** [mviewer/mviewer#729]
## Environnement

Version mviewer: 3.9.1

Navigateur: Firefox 109

## Description

Si la valeur "url" de proxy n'est pas nulle, la variable `_proxy` retournée par `configuration.getProxy()` (fichier `mviewer.js`, l. 271) n'est pas nulle non plus.
Conséquence : lors de l'appel à une requête du type GetFeatureInfo sur une couche WMS, *et malgré une valeur `useproxy` false par défaut pour l'élément `layer`*, l'url du proxy est quand même ajoutée à la requête.

Pour avoir un peu creusé, je dirais que le problème est situé dans le fichier `mviewer.js`, méthode `_ajaxURL()` :
```javascript
  var _ajaxURL = function (url, optionalProxy) {
    // relative path
    if (url.indexOf("http") != 0) {
      return url;
    }
    // same domain
    else if (url.indexOf(location.protocol + "//" + location.host) === 0) {
      return url;
    } else {
      // Test manuel
      console.log("Test proxy : ", optionalProxy, _proxy)
      if (optionalProxy) {
        return optionalProxy + encodeURIComponent(url);
      } else if (_proxy) {
        // Si la valeur `url` de l'élément `proxy` dans la config XML n'est pas nulle, l'URL renvoyée est du type <url-proxy>/url
        return _proxy + encodeURIComponent(url);
      } else {
        return url;
      }
    }
  };
```

Lors d'une requête `GetFeatureInfo` sur une couche WMS standard (avec le paramètre `useproxy=false` ou non défini), la console me renvoie :
`Test proxy :  undefined http://localhost:8080/proxy/`

Je noté des appels à cette méthode sous la forme `mviewer.ajaxURL(layer.url, _proxy)` donc je ne suis pas sûr de comprendre pourquoi la condition  ` else if (_proxy)` ci-dessus est quand même testée, mais il me semble que ça crée un conflit.

## Ce que je devrai voir

Pour un élément `<layer />` de la config XML, la valeur de `useproxy` est `false` par défaut.
Malgré la définition d'un proxy (url non nulle), les couches dont le paramètre `useproxy` n'est pas spécifié à `true` ne devraient pas passer par le proxy.

## Etapes

1. Créer une application mviewer par défaut
2. Créer une couche par défaut avec l'URL d'un flux WMS
3. Définir un proxy (avec une URL != "") même s'il n'est pas utilisé
4. Afficher la couche et sélectionner une feature
5. L'URL appelée est de la forme <url_proxy>/<url_couche>

**Comment by Gaetanbrl** [comment]
Merci pour cette issue.
Je n'utilise pas de proxy et aucun proxy n'est donc rajouté aux appels URL... à analyser donc.

Vous avez une config exemple qui vous a permis de voir le soucis ?

**Comment by benjaminh** [comment]
Vous pouvez tester avec la démo GéoBretagne, en ajoutant simplement un proxy fictif et non utilisé :

```
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <application mapfishurl="https://geobretagne.fr/mapfishapp/" home="https://cms.geobretagne.fr/" studio="http://kartenn.region-bretagne.fr/mviewerstudio/?xml=" title="Démo GéoBretagne" logo="img/logo/g.png" help="demo/demo_geobretagne_help.html" showhelp="true" exportpng="false" style="css/themes/pink.css"/>
    <mapoptions maxzoom="20" projection="EPSG:3857" center="-198478,6137005" zoom="14" projextent="-20037508.342789244, -20037508.342789244, 20037508.342789244, 20037508.342789244"/>
    <baselayers style="default">

    <baselayer 
      type="WMTS"
      id="ortho1"
      label="Photo aérienne actuelle"
      title="GéoBretagne"
      thumbgallery="img/basemap/ortho.jpg"
      url="https://tile.geobretagne.fr/gwc02/service/wmts"
      layers="satellite"
      format="image/jpeg"
      visible="true"
      style="_null"
      matrixset="EPSG:3857"
      fromcapacity="false"
    />
    
    </baselayers>
    <proxy url="http://localhost:8080/proxy"/>
    <searchparameters localities="false"/>
    <themes mini="false">
    <theme name="Randonnée" id="rando" icon="fas fa-blind">
        <layer
          id="pdipr_35"
          name="PDIPR 35"
          visible="true"
          tiled="false"
          queryable="true"
          fields=""
          aliases=""
          expanded="true"
          infoformat="text/html"
          featurecount="1"
          style="cd35:PDIPR35-Pedestre,cd35:PDIPR35-Equestre"
          stylesalias="Réseau pédestre,Réseau équestre"
          attributefilter="true"
          attributefield="REVET"
          attributevalues="Terre,Empierré,Goudron"
          attributelabel="Revêtement"
          attributestylesync="false"
          attributefilterenabled="false"
          url="https://geobretagne.fr/geoserver/cd35/wms"
          attribution="GéoBretagne"
          metadata="https://geobretagne.fr/geonetwork/apps/georchestra/?uuid=075fbf9d-0511-4e99-8bca-fabc13a0cf40"
          />
    </theme>
    </themes>
</config>
```

**Comment by Gaetanbrl** [comment]
Pourquoi rajouter un proxy fictif @benjaminh ?

**Comment by benjaminh** [comment]
@Gaetanbrl juste pour le test. Dans mon cas, j'en ai besoin, mais pas pour toutes les couches, or à partir du moment où il est déclaré, il est utilisé pour toutes les couches, peu importe la valeur de `useproxy`.

**Comment by Gaetanbrl** [comment]
Ce fonctionnent n'est peut être pas optimal et pourrait avoir un contrôle sur la valeur mais en l'état ca me semble pas incohérent.
Si pas de proxy -> Pas de config de proxy.

Pas de config inutile.

**Comment by benjaminh** [comment]
Je ne suis pas sûr de comprendre, mais le problème vient du cas où il y a nécessité d'utiliser un proxy, *mais pas pour toutes les couches*.
Du coup, le cas d'usage est le suivant :
- j'ai besoin d'utiliser un proxy pour certaines couches, je déclare donc dans ma config XML une url pour le proxy, et passe le paramètre `useproxy` à true pour les couches concernées
- pour les couches non concernées, je laisse le paramètre `useproxy` non renseigné pour ne pas utiliser le proxy.
Le problème c'est que pour ces dernières, mviewer appelle quand même le proxy lors des requêtes GetFeatureInfo.

**Comment by Gaetanbrl** [comment]
> Le problème c'est que pour ces dernières, mviewer appelle quand même le proxy lors des requêtes GetFeatureInfo.

C'est plus clair, merci du détail.

Si vous avez un correctif, vous pouvez faire une pull request, je testerai votre modification.

**Comment by benjaminh** [comment]
@Gaetanbrl J'ai essayé de faire simple, en espérant qu'il n'y ait pas d'effet de bord (je n'ai pas vu de batterie de tests à faire tourner). Vous me direz si des modifications complémentaires sont à prévoir (c'est la première fois que je propose une pull request).

Je précise que j'ai simplement ajouté la vérification de la présence du paramètre `useproxy` avant de faire la requête Ajax correspondant à un GetFeatureInfo, auquel cas, je passe la valeur du proxy. Et j'ai supprimé la vérification qui me semblait poser problème. À discuter si besoin
