### ISSUE TITLE
Option coordinate en degrés décimaux

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#730]
**Présentation**

L'option coordinate de l'application permet d'afficher les coordonnées du point sur lequel on clique. 
Les coordonnées sont affichées en degré/minute/seconde : 
![image](https://user-images.githubusercontent.com/5269430/216295502-ff392b32-28e3-4d29-b897-3a8ace7df8de.png)

**Description fonctionnelle**

Suite à concertation avec 2 utilisateurs de cette fonctionnalité (et en accord), je propose d'afficher les coordonnées en degrés décimaux.

Êtes-vous ok ?

**Comment by Gaetanbrl** [comment]
On pourrait choisir le format avec un paramètre ?

**Comment by lecault** [comment]
Oui mais tu penses que ça intéresse quelqu'un en degré minute seconde ?

**Comment by Gaetanbrl** [comment]
@hsquividant tu vois un usage des degrès minute seconde chez vous ?

**Comment by hsquividant** [comment]
> @hsquividant tu vois un usage des degrès minute seconde chez vous ?

A priori non, mais pourquoi ne pas maintenir les 2 options, DD et DMS ?

**Comment by Gaetanbrl** [comment]
D'un côté oui on peut supprimer une option qu'on pense inutile.
De l'autre elle est inutile faute de preuve du contraire.

Je préfèrerai garder les deux également. L'intérêt que je vois des DD, c'est pour fournir des coordonnées reportables dans un système de navigation.

**Comment by lecault** [comment]
Actuellement on a coordinates="true"

Si on garde les 2 options, on met au choix :
1/ coordinates="dms" coordinates="dd"
2/ coordinates="true" coordinatestype="dms" coordinatestype="dd"

La logique du code voudrait l'option 2

**Comment by Gaetanbrl** [comment]
> La logique du code voudrait l'option 2

C'est vrai qu'il y a des paramètres qui fonctionnent comme ca...

Après je me dis que pour simplifier, si on met aucune valeur c'est qu'on ne l'active pas, et inversement (option 1 du coup)

**Comment by Gaetanbrl** [comment]
> a été développé par Sébastien chez nous à l'époque pour les VN

@lecault c'est le type de coordonnées pour se repérer avec les cartes de nav maritime.

https://truesailor.com/apprendrelavoile/coursdevoile/navigationvoile/les-coordonnees-gps.php
