### ISSUE TITLE
Doc - Cohérence mviewer / mviewerstudio

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewer#734]
## Présentation

Dans le cadre des travaux en cours, il est demandé de mettre à jour les paramètres mviewerstudio et de mettre à jour la documentation mviewer pour afficher les paramètres compatible mviewerstudio :

* Voir description :

https://github.com/mviewer/mviewerstudio/issues/157#issue-1570012076

* Voir demande : 

https://github.com/mviewer/mviewerstudio/issues/157#issuecomment-1424231910

## Description détaillée

Mettre à jour la documentation avec ces nouveaux paramètres, qu'une fois la release mviewerstudio sera disponible avec les nouveaux paramètres mviewer intégrés.

**Comment by lecault** [comment]
Pour moi ça été fait non ?

Exemple : 

![image](https://github.com/mviewer/mviewer/assets/5269430/13fae9a8-cfd6-4a59-b631-052096cb6b73)

**Comment by Gaetanbrl** [comment]
Tout à fait, j'avais oublié cette issue.. merci @lecault !
