### ISSUE TITLE
[Sécurité] mviewer et web application firewal

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewer#750]
Retour d'expérience.
Je me suis fait blacklisté par une collectivité pour avoir visité le mviewer de cette collectivité (Région Bretagne)
Cette collectivité dispose d'un système de sécurité (WAF) qui détecte un comportement de mviewer comme une tentative de dérobage d'informations critiques (chargement au démarrage d'un fichier .env)
Je propose donc de renommer le fichier .env en un nom moins critique (environnement)

**Comment by Gaetanbrl** [comment]
Merci @spelhate - à traiter rapidement.
