### ISSUE TITLE
Décalage des boutons utilitaires

### ISSUE THREAD

**Issue by bdavid-rennesmetrpole** [mviewer/mviewer#756]
Mettre en place un déplacement des #backgroundlayerstoolbar-gallery, #zoomtoolbar, et #toolstoolbar lorsque le right-panel ou le bottom-panel sont activés

Lorsque le right-panel s'ouvre, décale les boutons en même temps pour les rendre toujours accessibles.
Pareil avec le bottom-panel

Exemple:

```
               #page-content-wrapper:has(#right-panel.active) #backgroundlayerstoolbar-default{
			margin-right: 320px;
			transition: 0.5s;
		}

		#page-content-wrapper:has(#bottom-panel.active) #backgroundlayerstoolbar-default{
			margin-bottom: 340px;
			transition: 0.5s;
		}
```

Cela concerne uniquement le positron.

Question, il est possible de le faire également avec la carte, pour recentrer le tout. Voulez vous que ce soit fait de manière automatique ou via un élément activable dans le xml par exemple ?

**Comment by cbriand** [comment]
Après discussion avec Benoit, nous partons sur la solution suivante : 
- décalage des boutons aujourd'hui cachés à l'ouverture d'un panneau d'information (panneau de droite ou panneau du bas)
- décalage de la carte à l'ouverture d'un panneau d'information activable ou non par un paramètre d'application. Le décalage de la carte peut parfois être perturbant et il est préférable d'avoir la main sur cette option. Par défaut, ce décalage sera désactivé.

**Comment by Gaetanbrl** [comment]
Merci pour cette issue 👍 !

> décalage des boutons aujourd'hui cachés à l'ouverture d'un panneau d'information (panneau de droite ou panneau du bas)

Comment souhaitez-vous déclencher la modification de la position, et selon quelle mesure (unité) calculée ?

Même question pour la carte.

> Par défaut, ce décalage sera désactivé.

Parfait je pense :)

**Comment by lecault** [comment]
> Après discussion avec Benoit, nous partons sur la solution suivante :
> 
> * décalage des boutons aujourd'hui cachés à l'ouverture d'un panneau d'information (panneau de droite ou panneau du bas)
> * décalage de la carte à l'ouverture d'un panneau d'information activable ou non par un paramètre d'application. Le décalage de la carte peut parfois être perturbant et il est préférable d'avoir la main sur cette option. Par défaut, ce décalage sera désactivé.

Ok pour moi

**Comment by bdavid-rennesmetrpole** [comment]
Voir https://github.com/mviewer/mviewer/pull/758/
