### ISSUE TITLE
Le Retour d'un getfeatureinfo d'un service WMS ne fonctionne pas et pas de retour d'erreur ?

### ISSUE THREAD

**Issue by jerbou** [mviewer/mviewer#760]
Bonjour,

J'ignore si c'est un bug.

## Environnement

Version mviewer: 3.4.1

Navigateur: firefox / version : 113.0.2

## Description
La carte suivante doit exposer un flux WMS externe 
https://cartes.ternum-bfc.fr/?x=651887&y=6004241&z=11.161933012937425&l=sigognenature_mares*&lb=altitude&config=apps%2Fagence-regionale-du-numerique-et-de-l-intelligence-artificielle-arnia%2Ftest-sigogne.xml&mode=d

le flux en question
https://www.sigogne.org/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities
l'id de la couche  : sigogne:nature_mares
Peut être que je me suis mal pris pour récupérer le flux et saisir cela dans mviewer.

## Ce que je devrai voir
des erreurs en retour dans la console, mais je ne constate rien.

## Etapes
lancer, cliquer sur un objet, et on constate que le volet d'information ne s'affiche pas et le navigateur ne renvoie rien.

D'avance merci pour vos retours.

**Comment by spelhate** [comment]
Salut. Tu as configuré un proxy pour ton mviewer ?
Je vois que `https://studiocarto.ternum-bfc.fr/studiocarto/proxy/?url=` est appelé mais que ça retourne une erreur 500

**Comment by jerbou** [comment]
merci de ta réponse rapide, j'ai essayé en mettant le proxy, et du coup cela bloque aussi l'appel des geométries :
https://cartes.ternum-bfc.fr/?config=apps/agence-regionale-du-numerique-et-de-l-intelligence-artificielle-arnia/test-sigogne.xml#

je suis "bloqué" avec ce flux...

**Comment by spelhate** [comment]
Pourtant je les vois les géométries : 
![image](https://github.com/mviewer/mviewer/assets/1793792/cf8e4007-6a2b-4e74-9e54-7183227a4e07)

**Comment by lecault** [comment]
Avec le proxy je vois bien les mares mais erreur 500 à l'interrogation : https://studiocarto.ternum-bfc.fr/studiocarto/proxy/?url=https%3A%2F%2Fwww.sigogne.org%2Fgeoserver%2Fows%3Fservice%3Dwms%26version%3D1.1.1%26request%3DGetCapabilities%26SERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetFeatureInfo%26FORMAT%3Dimage%252Fpng%26TRANSPARENT%3Dtrue%26QUERY_LAYERS%3Dsigogne%253Anature_mares%26LAYERS%3Dsigogne%253Anature_mares%26STYLES%3D%26TILED%3Dtrue%26INFO_FORMAT%3Dapplication%252Fvnd.ogc.gml%26I%3D31%26J%3D76%26WIDTH%3D256%26HEIGHT%3D256%26CRS%3DEPSG%253A3857%26BBOX%3D626172.1357121654%252C5987771.047747567%252C645740.0149531706%252C6007338.926988573

je vois qu'il y a un owsoptions jamais utilisé

**Comment by jerbou** [comment]
merci pour ton retour. j'avoue que avoir activé le owsoption sans trop savoir ce que c'est.

**Comment by spelhate** [comment]
Je viens de tester la couche dans le nouveau studio 👍 
https://delib.csm.ovh/mviewer/#prod/megalis/sigogne
Visiblement il n'y a pas besoin de proxy.

**Comment by jerbou** [comment]
Merci pour le retour @spelhate 
Ca viendrait de notre version de mviewer ?

**Comment by jerbou** [comment]
Merci ! It works !
https://cartes.ternum-bfc.fr/?config=apps/agence-regionale-du-numerique-et-de-l-intelligence-artificielle-arnia/test-sigogne-juin-2023.xml

en fait, nous avons par défaut la ligne <proxy url='https://studiocarto.ternum-bfc.fr/studiocarto/proxy/?url='/> dans le studio
en laissant la ligne, cela retournait la vilaine erreur 500
