### ISSUE TITLE
Résultats de recherche entités et adresses mélangés

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#762]
## Environnement

Version mviewer: 3.9.2

Navigateur: chrome / firefox

## Description

Lorsque j'effectue une recherche dans une application où à la fois la recherche d'adresse et d'entité sont activées, le résultat à l'écran n'est pas correct : 

![image](https://github.com/mviewer/mviewer/assets/5269430/4bc93201-47a3-47c5-8d15-82e1bf13edd5)

## Ce que je devrai voir

Les résultats d'adresse en dessous de localités et les entités en dessous d'entités

## Etapes

1. Ouvrir Kartenn VN : https://kartenn.region-bretagne.fr/vn/
2. Effectuer une recherche, exemple gacet
3. Voir le résultat

Pour information j'ai le même comportement pour une recherche d'entité fuse qu'ELS.
C'est une régression.

**Comment by spelhate** [comment]
C'est bien possible.  Je vais regarder.

**Comment by lecault** [comment]
Je confirme le lien avec le commit : si je remet le search.js comme avant, je n'ai plus le soucis.
