### ISSUE TITLE
Résultat de recherche en mode ultra simplifié non visible

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#763]
## Environnement

Version mviewer: 3.9.2

Navigateur: chrome / firefox

## Description

Lorsqu'on ouvre une carte en mode ultra simplifié, le résultat de recherche n'apparaît pas alors que cela fonctionne dans les autres modes.

![image](https://github.com/mviewer/mviewer/assets/5269430/df1b43ea-ccce-4c7c-b371-eeaca3ec6efa)

## Ce que je devrai voir

Voir le résultat de recherche.

## Etapes

1. Ouvrir https://kartenn.region-bretagne.fr/kartoviz/?x=-255516&y=6140243&z=8&l=circonscription_academique*%2Caire_educative*aire_educative_nature&lb=positron&config=apps/region/ame/ame.xml&mode=u
2. Taper Rennes dans la recherche et constaté que le résultat ne s'affiche pas. Par contre, la requête renvoie bien le résultat : https://api-adresse.data.gouv.fr/search/?q=rennes&limit=5&lon=-2.295339281370836&lat=48.200302734546284

**Comment by spelhate** [comment]
Peut être un lien avec #762

**Comment by fgravin** [comment]
Bonjour, @spelhate @lecault je dois faire une PR sur `master` ou `develop` pour les bugs fix ?

**Comment by lecault** [comment]
Bonjour Florent.
Sur develop
