### ISSUE TITLE
ALERTE!! COMMIT SUR BRANCHE MASTER

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewer#765]
## Environnement

Version mviewer: master

## Description

Un commit a été directement réalisé sur la branche master (non présent sur la branche develop) :

https://github.com/mviewer/mviewer/commit/85817645b70569138870c8f41cec0b803ff8aeb8

Cette modification entraînera potentiellement un conflit lors de la prochaine release. Le risque est que ces modifications ne soient pas prises en compte lors des développement sur la branche develop, voir écrasées.

Cette action est à reporter directement sur la branche develop.

La prochaine release permettra de disposer de ce commit sur la branche master.

## Ce que je devrai voir

Aucun commit individuel sur master non présent dans develop (hors exception type merge commit de release).

**Comment by Gaetanbrl** [comment]
# comment corriger ce cas de figure ?

1. Déplacer le commit de master vers develop

```
cd /mviewer
git checkout develop
git pull
git cherry-pick 85817645b70569138870c8f41cec0b803ff8aeb8
git commit push -f
```

Contrôler que l'historique de la branche develop comporte bien le dernier commit rajouté.

2. Revenir en arrière sur le dernier commit de la release

```
cd /mviewer
git checkout master
git reset --hard 1f655de1c93a614d1db20b4ba804f27927a98a8e
git push -f
```

Contrôler que l'historique de la branche master est bien sur le commit désiré et que le commit indésirable n'y figure plus.

**Comment by smevel** [comment]
Erreur réparée :(

**Comment by Gaetanbrl** [comment]
Merci @smevel , je viens de faire la modification sur la branche master.
J'ai également vu que les sécurité sur le dépôt ne permettait pas de faire un push forcé.

Donc impossible de remettre la branche master ISO avec la dernière release.

J'ai remis cette possibilité de faire un push forcé. J'ai remis comme il faut :)
