### ISSUE TITLE
Template Mst et comportement carroussel (mviewer 3.4.1)

### ISSUE THREAD

**Issue by jerbou** [mviewer/mviewer#767]
**Question / description**
Bonjour,

je rencontre une difficulté pour mettre en forme un template mst qui comprend également un carrousel (dles flèches pour passer d'un objet à un autre, dont le nombre est défini par feature_count).

[voici l'exemple qui ne fonctionne pas ](https://cartes.ternum-bfc.fr/?config=apps/agence-economique-regionale-bourgogne-franche-comte-aer-bfc/entreprises_carrousel_mst_ko.xml
)

le template mst en question : 
https://cartes.ternum-bfc.fr/apps/agence-economique-regionale-bourgogne-franche-comte-aer-bfc/mst/entreprises.mst

Avez vous des idées pour y remédier pour avoir un mst pas mal qui prenne en compte le carroussel ?

Merci !

Décrivez votre message ici, nous vous répondrons dès que possible 😉.

**Comment by jerbou** [comment]
J'ai suivi la documentation 
https://mviewerdoc.readthedocs.io/fr/stable/doc_tech/config_tpl.html

mais rien n'y fait ou je ne comprends pas mes erreurs.

**Comment by Agath21** [comment]
Bonjour @jerbou , 

Je crois que tu as une balise `<i>` mais qui n'est jamais fermée (il manque `</i>`) à la fin de ton template dans la div `id="réalisation"`. Peux-tu retester après avoir corrigé ce problème ? 

Au passage, il n'est pas conseillé de mettre des accents dans les classes ou id des div html comme pour `id="réalisation"` :)

Belle journée, 
Agathe

**Comment by jerbou** [comment]
Merci beaucoup @Agath21 ! 
Ca marche effectivement parfaitement !
