### ISSUE TITLE
Bug affichages couches groupées et non groupées dans une même thématique

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewer#768]
## Environnement

Version mviewer: 3.9.1

FF: 102.11 esr

## Description

Si une thématique comporte au moins un groupe de couches et une ou plusieurs couches non groupées, seules les couches groupées sont affichées dans la TOC

## Ce que je devrai voir

Au même niveau et pour une même thématique, les groupes et les couches non groupées

## Etapes

Créer une thématique avec une couche et un groupe de couches contenant également une couche

**Comment by LPoin** [comment]
PR en attente -> https://github.com/mviewer/mviewer/pull/920
