### ISSUE TITLE
Typo dans la documentation

### ISSUE THREAD

**Issue by olivier-maury** [mviewer/mviewer#778]
En parcourant la documentation, j'ai relevé quelques fautes de frappe et autres.

Si personne n'annonce être sur la relecture en ce moment, après avoir tout lu, une PR sera faite.

**Comment by Gaetanbrl** [comment]
@olivier-maury en effet, je ne pense pas qu'il y ait de modification de la document en ce moment sur la branche develop (branche à modifier).

Un grand merci pour votre contribution ! 👍
