### ISSUE TITLE
Question : peut-on customiser le contenu du volet du bas quand on clique bsur un objet d'une couche ? 

### ISSUE THREAD

**Issue by laurentateegle** [mviewer/mviewer#782]
Bonjour,
Tout d'abord, bravo pour le travail accompli, c'est remarquable. 
Je souhaiterai savoir si on peut complètement customiser le contenu du volet du bas quand on clique sur un objet d'une couche ? Par exemple, j'affiche une liste de polygones, Au click d'un polygone, je veux afficher un tableau de bord construit à partir de données issues d'un back-end tiers. 

Question complémentaire, est-il possible d'ajouter d'autres fenêtres dans l'interface utilisateur ? Par exemple, je souhite ajouter un volet de gauche avec une vue arborescente organisée d'une de mes couches.

Merci par avance

**Comment by Agath21** [comment]
Bonjour @laurentateegle ,

Merci pour votre retour, c’est toujours motivant 😊 

La solution mviewer est plutôt modulable et souple, vous pouvez donc aisément personnaliser le contenu de la fenêtre d’information (bas ou droite), matérialisé par un fichier mustache (`.mst`), si vous maîtrisez les langages web `html`, `css` et `js`. 

A titre d’exemple, vous pouvez consulter [cette application de Mégalis Bretagne](https://geobretagne.fr/mviewer/?config=/apps/megalis-services/config.xml#). En sélectionnant la couche OpenData et en cliquant sur une entité, vous visualisez une première information et si vous cliquez sur un des boutons "réutiliser", une autre fenêtre s’affiche. Il existe quelques exemples qui mobilisent des fichiers` .mst` relativement complexes avec des affichages avancés sur[ le site web](https://mviewer.netlify.app/fr/).

Quant à l’ajout d’une fenêtre supplémentaire, il faut se tourner vers des [customcomponents](https://mviewerdoc.readthedocs.io/fr/latest/doc_dev/customcomponent.html#customcomponent) qui permettent de personnaliser la solution et d’ajouter des fonctionnalités. C’est le cas par exemple des addons [filter](https://kartenn.region-bretagne.fr/kartoviz/?config=demo/filter/filter.xml) ou [stats](https://kartenn.region-bretagne.fr/kartoviz/?config=demo/stats/stats.xml). 

N’hésitez pas à tester les démos accessibles [ici](https://kartenn.region-bretagne.fr/kartoviz/demo/) et regarder la manière dont elles sont construites dans le dossier `demo/addons` du code source.

Belle journée, 
Agathe

**Comment by Agath21** [comment]
@laurentateegle , 

Il n'est pas nécessaire d'adhérer à GéoBretagne, mviewer peut être utilisé librement par n'importe qui. 

Pour tester l'app, il existe plusieurs solutions :
- Déploiement dans un environnement web, présenté [ici](https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/deploy.html)
- Déploiement dans un environnement local, à l'aide de l'outil XAMPP par exemple. Vous copiez/clonez le code mviewer dans le dossier `htdocs` et vous accédez à l'application locale par défaut via ce lien : [http://localhost/mviewer/](http://localhost/mviewer/demo/) 
- Déploiement dans un environnement de test en ligne, à l'aide de ces astuces : #677 #690
