### ISSUE TITLE
MViewer & Postgis

### ISSUE THREAD

**Issue by cotegeo** [mviewer/mviewer#784]
### Discussed in https://github.com/mviewer/mviewer/discussions/783

<div type='discussions-op-text'>

<sup>Originally posted by **cotegeo** September 13, 2023</sup>
Bonjour,

Je (re)découvre MViewer, et je voudrais savoir s'il est possible d'avoir des couches PostGreSQL/PostGIS, voire des tuiles vectorielles. En effet, je travaille avec des API qui proposent la génération de tuiles vectorielles.

Merci pour vos retours

Sylvain BECQUAERT</div>

**Comment by lecault** [comment]
Voir dans l'onglet discussion
