### ISSUE TITLE
Compilation doc KO

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#792]
**Présentation**

Suite à une évolution de readthedoc https://docs.readthedocs.io/en/stable/config-file/v2.html la compilation de la doc ne fonctionne plus. 

![image](https://github.com/mviewer/mviewer/assets/5269430/8c0e3c61-299d-4f7a-8c00-3a4795c64de4)

**Comment by Gaetanbrl** [comment]
Fichier à tester poussé sur develop (test à réalisé via IHM admin ReadTheDoc @lecault ) :

https://github.com/mviewer/mviewer/commit/bc7d8fb69e0fd85bd8c52e16791b4ed575ff1545

**Comment by lecault** [comment]
Doc testable ici : https://mviewerdoc.readthedocs.io/fr/latest/
La compilation fonctionne.
