### ISSUE TITLE
Optimisation du style pour une impression simple et lisible depuis le navigateur

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewer#793]
## Présentation

En tant qu'utilisateur je souhaite imprimer la carte depuis la fonction "Imprimer" du navigateur :
1 - Je configure ma carte (zoom et centrage + interrogation si souhaitée) 
2 - Ctrl + P 
3 - Une fenêtre s'ouvre avec l'aperçu de l'impression + options
4 - J'imprime ou j'exporte ma carte en .pdf

### Aperçu actuel 
![image](https://github.com/mviewer/mviewer/assets/22764056/a922e84b-dae4-4534-893f-5d8d6a3d7c90)

### Aperçu optimisé
![image](https://github.com/mviewer/mviewer/assets/22764056/b0dbd699-8496-42df-80b7-cf1d97d16368)

##  Description technique

Cette optimisation nécessite l'ajout de propriétés spécifiques à l'impression afin de gérer : 
- l'affichage des blocs principaux (carte, légende, templates)
- La suppression des composants non essentiels comme le menu, les boutons d'actions .. 

## Questions 

Ce travaille est réalisé en parallèle du développement du module d'impression, il est donc financé par ARNIA- IDeO BFC également. Lors de nos échanges avec @jerbou, nous avions deux questions auxquelles nous aimerions avoir un avis de la communauté :

**Question 1** 
Pour l'ajout des nouvelles propriétés, il existe 2 solutions : 
- Ajout au sein du fichier existant mviewer .css avec la balise `@media print{}`
- Création d'une nouvelle feuille de style dédiée à l'impression `<link rel="stylesheet" href="print.css" type="text/css" media="print">
`

**Question 2** 
Pour l'accès à ce type d'impression, est-il nécessaire de créer un nouveau bouton dans la `#toolstoolbar` en supplément du bouton "Exporter en .Png" et le futur plugin d'impression ? ou conserve t-on le fonctionnement classique du navigateur, c'est à dire le `CTRL+P` ?

Merci pour vos retours :)

**Comment by tbrunelle9** [comment]
Bonjour, 

Merci beaucoup pour ces évolutions et contributions qui je pense vont être utiles à beaucoup de personnes. 

Concernant les questions :

- Je serai plutôt d'avis d'un fichier .css dédié spécifiquement au module. Cela me semble plus facile pour le personnaliser.
- Concernant l'accès à l'impression, je serait plutôt d'avis de rajouter un bouton. Dans le paramétrage de l'application, on aurait donc le choix entre différentes manières d'exporter. D'autant plus que je ne suis pas sûr que le CTRL+P soit très intuitif. 

Merci encore pour ce travail 👍

**Comment by lecault** [comment]
Bonjour Agathe,

Et merci pour ce partage.

Concernant mon avis :
- je suis sensible à l'argumentaire de Tom sur la personnalisation
- là je serai d'avis que ce nouveau mode d'impression remplace l'actuel export PNG (et donc ne pas créer de nouveau bouton). Il a été développé à "l'arrache" et  ne semble pas convenir à un besoin spécifique.

Si je comprends bien à l'avenir on aura 2 façons d'imprimer : 
- Celle-ci avec CTRL+P ou un bouton impression rapide
- Un module d'impression plus complet en développement

**Comment by Agath21** [comment]
Ok c'est noté, merci pour vos retours.

> à je serai d'avis que ce nouveau mode d'impression remplace l'actuel export PNG (et donc ne pas créer de nouveau bouton). Il a été développé à "l'arrache" et ne semble pas convenir à un besoin spécifique.
Je partage également ton avis, l'export PNG a peu d'intérêt (de mon côté)

> 2 façons d'imprimer
Effectivement, c'est l'objectif ! Donc on aurait un bouton d'impression rapide via le navigateur (qui remplace l'export PNG) et un module d'impression développé sous forme de plugin

**Comment by Agath21** [comment]
Les développements de cette issue sont réalisés et visibles sur cette branche https://github.com/jdev-org/mviewer/tree/print-css

**Comment by Agath21** [comment]
Détails des développements :

- [ ] Création et intégration d'une nouvelle feuille de style print.css
- [ ] Ajout des propriétés de style
- [ ] Gestion des blocs (défaut, interrogation, légende)
- [ ] Modification du bouton d'export PNG pour une impression depuis le navigateur 
- [ ] Mise à jour de la documentation

**Comment by Agath21** [comment]
### Remarque 

Comme évoqué plus haut, il est souhaité remplacer le bouton d'export PNG vers un bouton "Imprimer la vue courante" permettant d'ouvrir la fenêtre d'impression du navigateur.  

Toutefois, au delà du développement technique, j'ai un problème avec l'identifiant `#exportpng` pour ce bouton
Si je remplace les fonctionnalités pour le même bouton, il me semble incohérent de laisser l'ID tel quel car il n'est plus représentatif de l'action associée. A contrario, si je modifie l'ID, cela a des impacts non négligeables sur les applications car c'est un paramètre du `config.xml` et cela nécessiterait une mise à jour du mviewerstudio également. 

Je fais donc le choix de conserver la fonction d'export PNG et de créer un nouveau paramètre `print=true/false` permettant de limiter les risques à mon sens. 

Il appartient ensuite à la communauté de mettre à jour ces applications pour intégrer cette nouvelle fonctionnalité.

**Comment by lecault** [comment]
Ok je comprends ton raisonnement.
Du coup, l'option exportpng sera déprécié et pour moi, sera à supprimer dans mviewer dans une version future : on ne va pas faire cohabiter 2 fonctions semblables. Si on laisse exportpng, il faudra qu'elle pointe sur le nouveau module d'impression. Discussion à avoir en PSC.

**Comment by Gaetanbrl** [comment]
L'avantage du PNG c'est que c'est 1 clic + la carte en PNG directement. C'est rapide pour un outil de "capture" qui n'est pas un outil d'impression + complet.

**Comment by jerbou** [comment]
> l'option exportpng sera déprécié et pour moi, sera à supprimer dans mviewer dans une version future

ok pour un échange au prochain PSC.

> Je fais donc le choix de conserver la fonction d'export PNG et de créer un nouveau paramètre print=true/false
ok selon moi pour continuer comme cela.
