### ISSUE TITLE
Intégration dans une application web

### ISSUE THREAD

**Issue by laurentateegle** [mviewer/mviewer#801]
Bonjour,

Encore bravo pour le travail accompli, on a une seule envie, l'utiliser !

Je cherche à intégrer le mviewer dans une application web (codée en vuejs. J'aimerais faire une intégration plus poussée qu'avec un simple iframe, notamment pour pouvoir communiquer avec d'autres parties de l'application.
Quelle serait la bonne manière de faire ?

Merci par avance

**Comment by pierrejego** [comment]
Bonjour, pour l'instant il n'y a pas encore de possibilité d'intégration via un "web-component" cela fait plusieurs fois que le sujet est abordé, c'est peut être un point à mettre dans la road map.

**Comment by Gaetanbrl** [comment]
> pour l'instant il n'y a pas encore de possibilité d'intégration via un "web-component"

Bonjour,
En effet, c'est une évolution ciblée pour une version future (à terme) du mviewer (lit + vue ?). Mais cela nécessite des réflexions sur l'ensemble de la solution dans une road map dédiée ou la road map générale en + de la planification des évolutions.

Mviewer est un outil qui doit rester simple à installer, à démarrer comme à configurer pour les profils utilisateurs (bien sur, la doc compense un effort technique à fournir).

Toutes les idées et participations sont les bienvenues pour faire évoluer mviewer :)

**Comment by Gaetanbrl** [comment]
> Quelle serait la bonne manière de faire ?

Pas simple de répondre, mais je pense que les étapes suivantes peuvent être envisagées (**à discuter**).

Il faudra déjà reprendre ce qui fonctionne dans l'existant et découper en différents composants ainsi que leur priorité avant de parler technique.

Par exemple, cibler des composants "coeur" comme :
- la carte
- le volet d'interrogation (il peut y en avoir plusieurs)
- le volet des légendes, le bandeau supérieur (nav ou header)
- le volet qui affichera les couches (des sous-volets pour les paramétrages simples ?)
- etc...

Pour chaque composant, on pourra ensuite définir de manière simple sa carte utilisateur :
- une histoire (Quel objectif ? Pour qui ? Comment ?)
- une complexité (pour quel utilisateur ?)
- est-ce que tout est visible ?

Enfin, on pourra penser au notions de personnalisation, fonctionnement pré-technique :

- les paramètres obligatoires (le minimum)
- les paramètres automatiquement calculés (à partir de quoi ?)
- les dépendances à d'autres composants (ex: les boutons de navigation doivent être liés à une carte)
- l'interface (identique à aujourd'hui mais en mode web component ?)

La dernière étape pourra consister à identifier une base technique et à réaliser des tests de faisabilité.

**Comment by laurentateegle** [comment]
Bonjour et merci pour cette réponse très complète.

Peut-être que pour commencer, je pourrais utiliser l'intégration iframe
mais j'ai besoin de pouvoir "injecter" des layers par l'extérieur, càd
depuis l'app qui intègre le mviewer. Est-ce possible de communiquer avec
l'api du mviewer en iframe ?

Merci par avance

**Comment by Gaetanbrl** [comment]
Avez-vous regardé la documentation du paramètre addLayer ?

https://mviewerdoc.readthedocs.io/fr/stable/doc_tech/config_intro.html?highlight=addLayer#parametres-d-url

**Comment by laurentateegle** [comment]
C'est intéressant et merci pour ce retour.

Ce que je cherche, c'est un outil plus dynamique. En gros, l'utilisateur
choisit des flux WMS sur des serveurs qui lui sont fournis (via une
interface de recherche puis les flux sélectionnés deviennent accessibles
via le volet gauche du mviewer.

**Comment by Gaetanbrl** [comment]
`addLayer` est un paramètre général qui permet d'ajouter des couches à partir de flux OGC. Activée, cette option permet également de rajouter une  couche via l'URL de l'application.

Je vous laisse tester concrètement si ce n'est pas déjà fait : 

https://kartenn.region-bretagne.fr/kartoviz/?config=demo/addlayers.xml

Le bouton  bouton "ajouter des données" à gauche permet l'ajout d'une couche.

La configuration de cet outil est par défaut dans le fichier `/data/ogc_csw_serve.json`.

> Attention : Les couches ajoutées dans la carte sont temporaires. Si vous rechargez l'application vous devez recommencer les ajouts via l'outil d'ajout.

**Comment by Gaetanbrl** [comment]
A noter que si votre outil Vue.js a un backend, il peut également manipuler le XML de configuration du mviewer (ou le créer depuis un template) et le déposer sur un serveur en tant que "sauvegarde".

C'est ce que réalise le mviewerstudio (générer du XML via une interface / un backend).

**Comment by laurentateegle** [comment]
Merci beaucoup
Ce serait sans doute la façon la plus propre de procéder, la mise à jour du
fichier XML de configuration est dynamique ?

**Comment by Gaetanbrl** [comment]
> la mise à jour du fichier XML de configuration est dynamique ?

Dans mviewerstudio ?

**Comment by laurentateegle** [comment]
Dans mviewer. Si je "pousse" un nouveau fichier XML, il faut à minima
recharger le mviewer ?

**Comment by Gaetanbrl** [comment]
Si vous déposez un nouveau fichier XML sur le serveur, il faut recharger la page (comme toute page web).

**Comment by laurentateegle** [comment]
Merci beaucoup,

C'est super clair. J'en profite pour vous demander s'il est possible
d'afficher des layers WMTS ?

Merci par avance

**Comment by Gaetanbrl** [comment]
> possible d'afficher des layers WMTS ?

Mviewer prend en charge par défaut les WMS, WFS, WMS-T (dimension temps selon le server carto), TMS (flux IGN surtout).
Le WMTS n'est pas proposé par défaut, vous devez passer par un custom layer. Si vous souhaitez faire une contribution pour que ce type de couche soit pris par défaut, ce serait intéressant pour la communauté.

**Comment by laurentateegle** [comment]
Bonjour,
Grâce à votre aide, je suis parvenu à un premier résultat. Je suis vraiment
bluffé par les capacités d'extension du mviewer.
J'en profite pour vous demander si les ressources que l'on voit des les
exemple issues de kartenn sont utilisables dans des applications tierces ?
Par exemple :
https://kartenn.region-bretagne.fr/kartoviz/apps/region/territoire/data/epci_simple.geojson
ou les ressources php sur les couches de données insee.

Merci par avance

**Comment by Gaetanbrl** [comment]
Si votre question porte sur la réutilisation de fichiers, il faut se référer à la licence du fichier en question.
Mais de base, le code sources mviewer est en GNU General Public License v3.0 :

https://github.com/mviewer/mviewer/blob/master/LICENSE

**Comment by laurentateegle** [comment]
Bonjour,
J'ai maintenant un backend ultra-light en node.js qui permet d'envoyer une version mise à jour du config.xml depuis mon application web. 
Ainsi, je peux conserver l'intégration iframe et mettre à jour les layers sans difficulté.
