### ISSUE TITLE
Dessin et masque

### ISSUE THREAD

**Issue by laurentateegle** [mviewer/mviewer#802]
Bonjour,

J'aimerais pouvoir dessiner un polygone sur la map ou en importer un (depuis une couche WFS par exemple) puis me servir de ce polygone pour masquer ce qu'il y a autour par exemple en opacifiant tout ce qu'il y a autour et laissant en laissant transparente la zone à l'intérieur du polygone.
Existe-t-il des outils pour réaliser ce genre de fonctionnalité ?.

Merci par avance

**Comment by pierrejego** [comment]
Bonjour,
Non ce type d'outils n'existe pas pour l'instant, mais cela devrait être réalisable sous la forme d'une extension.

**Comment by laurentateegle** [comment]
Bonjour et merci pour vos réponses. J'ai pu dessiner sur la carte Open Layers sous-jacente au travers d'un custom layer. Je proposerai les éléments dans une prochaine contribution
