### ISSUE TITLE
Chargement du html pour un customconstrol

### ISSUE THREAD

**Issue by laurentateegle** [mviewer/mviewer#803]
## Environnement

Version mviewer: 3.9.1

Navigateur: chrome

## Description

Je reproduis l'exemple du customcontrol heatmap. Quand je suis dans la fonction init, je récupère le composant html d'interaction (un select dans mon cas) via document.getElementId("id de mon composant")

## Ce que je devrai voir

Au premier chargement de la page, tout se passe bien. Je m'attends à ce que ce soit pareil pour les chargements suivants Or, il semble que cette méthode parte en erreur par la suite, comme si le html ne se chargeait plus. Le debugger montre en effet que mon js, ma config.xml et mon icone de légende sont chargés mais pas mon html. et le message qui s'affiche dans une dialog au chargement ne m'aide pas : error custom.control. Dans la console, j'ai un message      GET http://127.0.0.1:5500/demo/comnum/config.json 404 (Not Found)

Merci d'avance pour votre aide. Je peux vous envoyer les fichiers si besoin

**Comment by Gaetanbrl** [comment]
Il est possible que lorsque vous appelez `document.getElementId("id de mon composant")`, il ne soit pas encore disponible.
Nous avons régulièrement des effet d'asynchrone (liés à JavaScript + temps de chargement aléatoires). Si tout le HTML est bien chargé quand vous en avez besoin, alors aucun soucis. Mais si une partie n'est pas encore chargée et que votre customControl appel une partie du HTML pas encore disponible, vous aurez une erreur.
