### ISSUE TITLE
CustomLayer/Mviewer: symbologie d'une couche par regroupement de valeurs dans des classes

### ISSUE THREAD

**Issue by Celine-Da** [mviewer/mviewer#809]
Bonjour tout le monde,

Dans le xml de ma carte encore  en brouillon ( https://cartes.ternum-bfc.fr/apps/sm-du-parc-naturel-regional-du-morvan/test-chemins-ruraux_v1ok.xml ), je fais appel à une couche de type customlayer (lignes 104 à 117).
Dans cette couche, j'ai un champ nommé "protection" qui correspond à un nombre allant de 0 à 14 (c'est un score de protection sur des entités linéaires correspondant à des chemins ruraux).
Dans ma carte Mviewer, j'aimerais représenter les chemins ruraux de cette couche en classifiant les valeurs du champ "protection" dans 4 classes:
protection inférieure ou égale à 3 -->  protection faible
protection comprise entre 4 et 6: --> protection modérée
protection comprise entre 7 et 9: --> protection élevée
protection supérieure ou égale à 10 --> protection très élevée

Le problème c'est que je ne sais pas comment m'y prendre pour représenter  la donnée comme cela dans un javascript...
Pour le moment mon javascript n'est pas vraiment paramétrer, du coup les chemins ne s'affichent pas dans ma carte.. 
Pouvez-vous m'apporter quelques pistes pour réaliser cette symbologie, s'il vous plaît ?

Merci beaucoup pour l'aide :)

**Comment by Gaetanbrl** [comment]
Bonjour,
Pour classer les données, vous avez plusieurs possibilités dans mviewer.

### Via un SLD

Le fichier de style SLD permet de réaliser des classifications sur une couche publiée par le serveur Cartographique.
Dans de nombreux cas c'est suffisant sans passer par du JavaScript.

Voir la documentation :
https://docs.geoserver.org/stable/en/user/styling/sld/index.html

### Style via plusieurs SLD
Voici deux exemples avec la fonctionnalité Analyse, qui est en réalité une liste de choix de SLD à appliquer à la couche.

 - https://kartenn.region-bretagne.fr/kartoviz/?config=demo/sld.xml
 - https://kartenn.region-bretagne.fr/kartoviz/?config=demo/geobretagne.xml#

### Via un customlayer

C'est le cas le plus complexe mais courant dans le monde JavaScript / OpenLayers.
Pour bien comprendre la représentation avec OpenLayers, il faut commencer par prendre connaissance de ces deux ressources :

- La documentation utilisateur : https://openlayers.org/workshop/fr/vector/style.html
- Les exemples Openlayers : https://openlayers.org/en/latest/examples/?q=style
- la documentation technique (chercher ol/style à gauche) : https://openlayers.org/en/latest/apidoc/module-ol_style_Style-Style.html

Ensuite, il faut utiliser un style simple (partez du fichier mviewer/customlayers/commune.js), et enrichissez-le avec des classes de styles qui se basent sur des conditions, regardant bien [cette documentation](https://openlayers.org/workshop/fr/vector/style.html).

**Comment by tbrunelle9** [comment]
Bonjour, 
J'ai eu à faire ça pour une application, voici mon code adapté à votre problématique : 

`{
mviewer.customLayers.geocontrib_chemins_ruraux_brassy = {};
var geocontrib_chemins_ruraux_brassy = mviewer.customLayers.geocontrib_chemins_ruraux_brassy;

var colors = [
    'rgba(213, 64, 25,.6)', // protection faible
    'rgba(163, 158, 160,.6)', // protection modérée
    'rgba(17, 17, 17,.6)', // protection élevée
    'rgba(245, 124, 187, 0.8)' // protection très élevée
  ];
  

  var styleFunction = function(feature) {
    var value = (feature.get('protection')); // Récupérer la valeur du champ 

    var colorIndex = 0;
    if (value  < 4) { // protection faible
      colorIndex = 0;
    } else if (value >= 4 && value < 7) { // protection modérée
      colorIndex = 1;
    } else if (value >= 7 && value < 10) { // protection élevée
      colorIndex = 2;
    } else if (value >= 10) { // protection très élevée
      colorIndex = 3;
    }
    
    return new ol.style.Style({
        stroke: new ol.style.Stroke({ color: 'rgba(255, 255, 255, 1)', width: 0.8}),
        fill: new ol.style.Fill({
            color: colors[colorIndex]
        })
    });
  };

// Possibilité directement les flux IGN
mviewer.customLayers.geocontrib_chemins_ruraux_brassy.layer = new ol.layer.Vector({
        source: new ol.source.Vector({
           url: "FLUX A INSERER",
            format: new ol.format.GeoJSON()
        }),
        style:styleFunction
});
mviewer.customLayers.geocontrib_chemins_ruraux_brassy.handle = false;
}`

Probablement des retouches à faire, notamment le flux à insérer. 
En espérant que ça aide

**Comment by Gaetanbrl** [comment]
merci pour le partage @tbrunelle9.
Ca me fait penser que depuis la v3.7 (de mémoire) d'utiliser la classe customLayer pour en créé un : 

https://github.com/mviewer/mviewer/blob/c4508ceefdaca6de15c0aefdf1fa94f43da022d0/customlayers/lycee.js#L54

Par soucis de temps on a pas du mettre à jour les customlayers d'exemple.
Ca fonctionne aussi bien comme ca, mais on préfère utiliser la classe :)

**Comment by Gaetanbrl** [comment]
Je viens également de voir (via le rendu TIFF) que les couches peuvent être avoir un style écrit en Expression OpenLayers.

C'est pas forcément évident de bien comprendre / appliquer les expressions mais je pense que ca peut être + simple à écrire que du JavaScript.

- **Example**

https://openlayers.org/en/latest/examples/style-expressions.html

- **Doc**

https://openlayers.org/en/latest/apidoc/module-ol_style_expressions.html

**Comment by Gaetanbrl** [comment]
Je viens de faire un test sur cette syntaxe "Expression", et c'est pas trop mal.

Voici une classification réalisée sur les valeur de pixel de la bande 1 d'un tiff directement chargé dans openLayers (pas de serveur carto donc).

![image](https://github.com/mviewer/mviewer/assets/16317988/9b77672f-6081-47c9-ab01-d892be367568)

**Comment by Celine-Da** [comment]
Génial ! Merci beaucoup pour le partage de la documentation et du code!

J'ai repris le code en indiquant bien l'url de la donnée, j'ai modifié les couleurs RGBA et j'ai retouché cette partie pour bien correspondre à ma symbologie de ligne:
return new ol.style.Style({
            stroke: new ol.style.Stroke({ color: colors[colorIndex], width: 2}),
        });

La couche est bien appelée dans le mviewer et les classes bien visibles, c'est parfait ! Le code m'a vraiment aidé.
Par défaut, les tronçons font tous partis de la classe 1 car le score protection n'est pas encore renseigné dans geocontrib, ça sera aux contributeurs de le renseigner... Mais je vais les repasser en mode brouillon pour qu'ils ne soient pas visibles dans la carte mviewer mais uniquement lorsque les contributeurs auront publiés le score protection. 
En tout cas, j'ai dessiné grossièrement 4 tronçons avec des valeurs comprises dans chacune des classes et ça fonctionne bien :)

Maintenant je vais étudier un peu plus la doc pour essayer d'ajouter une légende à la donnée dans la carto mviewer ;) 
Encore merci !!

**Comment by Gaetanbrl** [comment]
Super. Je vous laisse fermer cette issue si vous avez votre solution.
