### ISSUE TITLE
[Plugin impression] Accès au plugin 

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewer#813]
## Histoire
En tant que utilisateur,
Je souhaite pouvoir imprimer ma carte depuis une nouvelle fenêtre avec un minimum d’options.

## Description détaillée
1.	Pour accéder au module d’impression, l’utilisateur clique sur le bouton en haut à droite avec un icône « imprimante ». 
2.	Lors du clique sur le bouton, une modale s’ouvre. 

## Avancement

- [x] Création du plugin 
- [x] Mise en place des dossiers et ressources nécessaires 
- [x] Affichage du bouton avec l’icône 
- [x] Création de la modale avec un titre

## Spécifications particulières 
- [x] Masquer l’accès au plugin en mode mobile 

## Tests à réaliser 

- [x] Affichage du bouton d’impression
- [x] Ouverture et fermeture de la modale

**Comment by jerbou** [comment]
je valide :

- [x]  Affichage du bouton d’impression
- [x] Ouverture et fermeture de la modale

**Comment by Gaetanbrl** [comment]
Merci pour ce retour @jerbou je clos l'issue.
