### ISSUE TITLE
[Plugin impression] Configuration du plugin 

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewer#815]
## Histoire
En tant que utilisateur,
Je souhaite pouvoir configurer mon gabarit d’impression

## Description détaillée
L’utilisateur configure son impression avec les paramètres suivants :
•	Affichage ou non des composants de la carte
•	Saisie du titre et du commentaire directement dans les blocs associés
•	Modification du cadrage de la carte

## Avancement
- [x] Saisie du titre
- [x] Saisie d’un commentaire
- [x] Saisie des informations dans le fichier de configuration du plugin et affichage dans le gabarit
- [x] Modification du cadrage de la carte

Gestion de l’affichage : 
- [x] Barre d’échelle 
- [x] Orientation
- [x] QR Code

## Tests à réaliser 

- [x] Saisie du titre
- [x] Saisie du texte
- [x] Modification du cadrage de la carte
- [x] Affichage / masquage des blocs barre d’échelle, orientation, QR Code
- [x] Validité du QR Code et redirection
- [x] Affichage dans le gabarit des informations saisies

## RAF

- [x] Corriger la suppresion du QR Code
- [x] Afficher la légende au changement d'orientation
- [x] Ajouter un width 100% sur les textearea -> remplacer textearea par contentEditable
- [x] Corriger l'affichage des block à la suppression d'un block

**Comment by jerbou** [comment]
hello, 


Sous firefox, Pour un utilisateur final, le comportement de la coche partage fonctionne de "manière curieuse", la décoche enlève le QR code mais pas le bloc partage. Serait-il possible que le comportement soit le même que la croix (supprimer le bloc).
![2023-11-16_13h43_56](https://github.com/mviewer/mviewer/assets/7600693/63f6da65-bd6d-4fdc-ae70-4f12744a5557)

**Comment by jerbou** [comment]
La suppression d'un bloc information ou d'un bloc commentaire (cliquer sur croix) entraine un changement dans les blocs.
La suppression des deux blocs entraine un déplacement du bloc carte en dehors du de la zone.
Est-ce que c'est possible d'améliorer ce comportement

![2023-11-16_13h54_44](https://github.com/mviewer/mviewer/assets/7600693/7b6a6453-3fd3-4d23-aeab-9f11ea19b8a6)

**Comment by Gaetanbrl** [comment]
> Est-ce que c'est possible d'améliorer ce comportement

oui ce n'est pas normal d'avoir les blocs qui bougent ainsi.
La suppression du bloc QRCode entrainera le même fonctionnement.

**Comment by Gaetanbrl** [comment]
> la décoche enlève le QR code mais pas le bloc partage

@jerbou  Je me questionne sur l'intérêt de la checkbox du QR code étant donné que c'est un bloc comme les autres avec une croix ?
Dans ce cas pourquoi ne pas avoir de checkbox pour les autres blocs également ?

**Comment by jerbou** [comment]
pour la saisie d'un titre, la zone cliquable n'est pas explicite à l'oeil.... Pour améliorer l'expérience utilisateur, il faut montrer cela.
un clic à un endroit ne permet pas la modification du titre.
un clic à un autre endroit entraine la modification du titre.

![2023-11-16_14h25_26](https://github.com/mviewer/mviewer/assets/7600693/a723fa02-b4f0-44fc-8402-7f524ada992d)

![2023-11-16_14h28_16](https://github.com/mviewer/mviewer/assets/7600693/1e7ecf02-3266-44c9-b159-0fa945a1a67c)

**Comment by jerbou** [comment]
En sélectionnant orientation portrait, l'affichage des couches dans le bloc légende ne se fait pas (sans aucune autre modif).

![2023-11-16_14h32_48](https://github.com/mviewer/mviewer/assets/7600693/43fb841b-5b12-42ce-923c-7c273f6de4d5)

**Comment by jerbou** [comment]
> > la décoche enlève le QR code mais pas le bloc partage
> > @jerbou  Je me questionne sur l'intérêt de la checkbox du QR code étant donné que c'est un bloc comme les autres avec une croix ?

Dans ce cas pourquoi ne pas avoir de checkbox pour les autres blocs également ?
Effectivement, pour faire propre, il faudrait des options avec légende / commentaire / informations.
C'est possible ?

**Comment by Gaetanbrl** [comment]
> C'est possible ?

Oui mais à mon sens c'est soit la croix soit la checkbox. Je ne vois pas l'intérêt des deux. La croix étant sûrement plus intéressante côté user.

**Comment by jerbou** [comment]
Pour une recette globale, les fonctions sont ok sur

- [x] Saisie du titre
- [x] Saisie du texte
- [x] Modification du cadre de la carte
- [x] affichage barre échelle, flèche du nord
- [x] affichage des informations saisies (bouton voir et bouton imprimer)
- [x] déplacement des blocs (j'ai compris que le déplacement se fait via l'élement, avec changement forme du curseur (encarte grisé carte par exemple)
- [x] le bouton réinitialise, réaffiche bien les blocs

**Comment by Gaetanbrl** [comment]
> Corriger la suppresion du QR Code
 >Afficher la légende au changement d'orientation
 >Ajouter un width 100% sur les textearea -> remplacer textearea par contentEditable
 
 Pour ces points, les modificaitions / correctifs sont disponibles sur gis.jdev (pf de test) @jerbou.
 
 Nous essayons de trouver comment corriger le positionnement des block à la suppression d'un des blocks.

**Comment by Gaetanbrl** [comment]
@jerbou si tu valides je clos.

**Comment by jerbou** [comment]
Merci pour les corrections.
J'ai noté que les options ne sont pas identiques en paysage, portrait.
En portrait, l'orientation (Nord) n'est pas disponible.

![2023-11-20_16h34_52](https://github.com/mviewer/mviewer/assets/7600693/e72432c1-135f-4274-84cf-ff942b8be01b)

**Comment by Gaetanbrl** [comment]
> J'ai noté que les options ne sont pas identiques en paysage, portrait.
> En portrait, l'orientation (Nord) n'est pas disponible.

Oui, comme expliqué dans la documentation, le template standard est à personnaliser (c'est une base, un exemple). Il ne contient pas tous les éléments en mode portrait afin de voir les différences.
Aux administrateurs de se saisir du système de template pour afficher ce qu'ils désirent. Du moins c'est ce que je propose pour la PR.

**Comment by jerbou** [comment]
ok, c'est noté.
Merci,
je peux donc clore ?

**Comment by Gaetanbrl** [comment]
Oui pour moi
