### ISSUE TITLE
[Plugin impression] Modification du gabarit initial

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewer#816]
## Histoire
En tant que utilisateur,
Je souhaite pouvoir modifier les blocs de mon gabarit d’impression

## Description détaillée
Pour personnaliser le gabarit d’impression, l’utilisateur peut effectuer les actions suivantes sur les différents blocs du gabarit :
•	Déplacement d’un bloc dans le canvas (en sélectionnant le titre du bloc en haut à gauche)
•	Modification de la taille (en sélectionnant l’icône « Resize » en bas à droite)
•	Suppression d’un bloc (hors carte et informations) (en cliquant sur l’icône « Poubelle » en haut à droite)

## Spécifications particulières 
•	Un bloc ne peut pas être déplacer en dehors du canvas
•	Les dimensions d’un bloc ne peuvent pas dépasser la taille du canvas (A4)
•	La suppression d’un bloc est définitive. Il faut fermer et rouvrir le plugin pour réinitialiser le gabarit.

## Avancement
Mise en place des mécaniques : 

- [x] Déplacement d’un bloc
- [x] Modification de la taille d’un bloc 
- [x] Suppression d’un bloc

## Tests à réaliser 

- [x] Déplacement d’un bloc
- [x] Modification de la taille d’un bloc 
- [x] Suppression d’un bloc
- [x] Impression du gabarit

**Comment by jerbou** [comment]
Je recette sous Firefox 119.0.1 et Chrome 119.0.6045.159
Les fonctionnalités ci dessous sont opérationnels :
- [x] Déplacement d’un bloc
- [x] Modification de la taille d’un bloc
- [x] Suppression d'un bloc
- [x] Impression du gabarit

**Comment by jerbou** [comment]
Dans les spéc, _les dimensions d’un bloc ne peuvent pas dépasser la taille du canvas (A4)_

Hors on peut pour le moment, redimensionner les blocs en dehors du gabarit A4.

![2023-11-16_15h06_21](https://github.com/mviewer/mviewer/assets/7600693/7f8445d9-bc2a-4705-b01e-eba2629a293c)

A l'écriture du bloc, je constate que la limitation fonctionne sur titre mais pas sur légende ou commentaire sous FF.

**Comment by Gaetanbrl** [comment]
> A l'écriture du bloc, je constate que la limitation fonctionne sur titre mais pas sur légende ou commentaire sous FF.

C'est en effet permis par le HTML. Je vais voir comment on peut limiter le resize. Dans tous les cas ils sont hors zone d'impression.

**Comment by Gaetanbrl** [comment]
> Si on pouvait "encadrer" les redimensionnement sur tout les blocs (comme c'est déja réalisé sur bloc titre et bloc carte)

Sur Chrome le comportement est identique : tous peut être resize hors de la zone d'impression

**Comment by Gaetanbrl** [comment]
@jerbou je ne vois pas de solution en l'état.

**Comment by Gaetanbrl** [comment]
> @jerbou je ne vois pas de solution en l'état.

Pour être plus précis, je n'ai pas vu de solution technique pour limiter le resize en dehors d'une div (non prévu par HTML/CSS visibement).

Dans tous les cas, seule la zone d'impression sera visible, donc pour moi ca a du sens de ne pas déborder du cadre.

**Comment by jerbou** [comment]
> > @jerbou je ne vois pas de solution en l'état.
> 
> Pour être plus précis, je n'ai pas vu de solution technique pour limiter le resize en dehors d'une div (non prévu par HTML/CSS visibement).
> 
> Dans tous les cas, seule la zone d'impression sera visible, donc pour moi ca a du sens de ne pas déborder du cadre.

ok, vu. Ne cherchons pas midi à quatorze heure. Un utilisateur final va aller au plus vite : éditer les blocs, supprimer ceux qui ne souhaitent pas afficher... le redimensionnement est fonctionnel et c'est déja cela.
Si des besoins de customisation avancé, cela sera pris en charge par "l'admin" Mviewer à travers les fichiers de config.

donc ok pour moi !

**Comment by lecault** [comment]
Salut,
Je viens de tester la démo et je n'ai pas de marge à gauche au niveau de la carte

![image](https://github.com/mviewer/mviewer/assets/5269430/9356e2ed-2604-4b8e-b6df-108dcd351c42)

**Comment by Gaetanbrl** [comment]
> Je viens de tester la démo et je n'ai pas de marge à gauche au niveau de la carte

Qu'à tu testé ?

**Comment by Gaetanbrl** [comment]
> A gauche, on devrait avoir une marge

Oui à gauche il serait préférable d'avoir une marge ;)
Aussi, l'impression papier "mange" un peu les bords et on va devoir rajouter un peu d'espace.

Merci pour ce retour.

**Comment by jerbou** [comment]
Merci pour le retour, Loic.
Est-ce que l'on peut améliorer la sortie PDF pour avoir une marge "partout", à gauche et à droite ?

Sous chrome et FF, une impression portrait génère un pdf en deux pages (dont une vide).

Sous FF, et Chrome, on clique sur imprimer en portrait, le pdf est generé.. si on change l'orientation en payse, les blocs ne se replacent pas avec le gabarit paysage... ?

**Comment by Gaetanbrl** [comment]
> Sous FF, et Chrome, on clique sur imprimer en portrait, le pdf est generé.. si on change l'orientation en payse, les blocs ne se replacent pas avec le gabarit paysage... ?

Sur le site de test on a bien le repositionnement des blocks même si on modifie la mise en page :
![blockposition](https://github.com/mviewer/mviewer/assets/16317988/2a4d2b2c-daae-46e9-9b1d-3c5f9fe013f7)

**Comment by jerbou** [comment]
je valide !
On peut merger donc !
