### ISSUE TITLE
[Plugin impression] Changer de gabarit

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewer#817]
## Histoire
En tant que utilisateur,
Je souhaite pouvoir changer de gabarit d’impression

## Description détaillée
Pour changer le gabarit d’impression, l’utilisateur peut sélectionner un autre modèle à l’aide de la liste déroulante. Dans le cadre de notre projet, cela concerne uniquement le changement d’orientation soit un gabarit pour le mode portrait en A4. 

_La communauté sera libre de proposer d’autres modèles pour enrichir le plugin ainsi qu’une nouvelle liste déroulante pour sélectionner ceux-ci._

## Avancement

- [x] Création d’un gabarit A4 Portrait
- [x] Mise en place de la mécanique pour changer de gabarit 
- [x] Création d’une liste de sélection « Orientation » dans la modale
- [x] Génération du PDF dans le format sélectionné

## Tests à réaliser 

- [x] Changer de gabarit à l’aide de la liste de sélection Orientation
- [x] Impression du gabarit  portrait A4

**Comment by jerbou** [comment]
En choisissant l'Orientation Portrait, les options de carte ne sont pas les mêmes que pour l'orientation Paysage.

![2023-11-16_15h13_36](https://github.com/mviewer/mviewer/assets/7600693/0987b546-9eab-4311-b626-8a52d3f944b0)

Le mode portrait affiche des blocs de manière ératique

![2023-11-16_15h16_05](https://github.com/mviewer/mviewer/assets/7600693/7c1d103f-79b6-4558-8d24-645f8ae99594)

Merci,

**Comment by Gaetanbrl** [comment]
> Le mode portrait affiche des blocs de manière ératique

On est en train de faire des modifications, je pense que j'ai poussé une des modifications qui a créé ce comportement sur le mode portrait. La disposition risque d'être un peu chamboulée le temps d'ajuster les dernières règles CSS.

**Comment by jerbou** [comment]
Je valide la modification apportée. Bravo !

**Comment by Gaetanbrl** [comment]
Ok je clos.
