### ISSUE TITLE
Demo KO - plugin Télécharger données KO

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewer#818]
## Environnement

Version mviewer: develop

## Description

La démo Télécharger des données (plugin) ne fonctionne pas :
https://kartenn.region-bretagne.fr/kartoviz/?config=demo/filter/filter_download.xml

**Comment by lecault** [comment]
Je viens de regarder je comprends pas...
Au pire on prendra une autre donnée.
Car la fonctionalité fonctionne toujours chez nous.

**Comment by lecault** [comment]
J'ai trouvé d'où vient le problème. En fait l'addon filter ne fonctionne pas si on a une seule couche. Si j'ajoute une autre couche dans la conf download, tout s'affiche
@Gaetanbrl je pense que ça vient de là : https://github.com/mviewer/mviewer/issues/757

**Comment by lecault** [comment]
Pour étayer le problème :
Ancien filtre : https://kartenn.region-bretagne.fr/kartoviz/?config=apps/region/rde/rde.xml
Nouveau filtre : https://kartenn.region-bretagne.fr/kartoviz/?config=apps/region/rde/rde_new_filter.xml

**Comment by Gaetanbrl** [comment]
> En fait l'addon filter ne fonctionne pas si on a une seule couche. Si j'ajoute une autre couche dans la conf download, tout s'affiche

Je n'avais pas vu ton issue, mais j'ai fais un correctif en regardant une autre issue (j'ai vu que la démo était KO...). A voir si ca marche maintenant sur develop @lecault

**Comment by Gaetanbrl** [comment]
> A voir si ca marche maintenant sur develop

Je dis ca mais j'ai quand même testé en local et je peux télécharger les données  🙈

**Comment by lecault** [comment]
Merci @Gaetanbrl
