### ISSUE TITLE
Demo KO - Cadastre

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewer#819]
## Environnement

Version mviewer: develop

## Description

Lorsque j'accède à la démo, je ne peux pas sélectionner de section, commune ou parcelle. Je ne peux sélectionner qu'une valeur de département.

## Ce que je devrai voir

Avoir la possibilité de sélectionner des valeurs de filtre pour les communes, sections, parcelle.

**Comment by lecault** [comment]
Tu parles de quelle démo ? 
Testé ici https://kartenn.region-bretagne.fr/kartoviz/?config=demo/cad/cad.xml ça fonctionne

**Comment by Gaetanbrl** [comment]
Je pense que je l'utilise pas bien alors ^^

**Comment by Gaetanbrl** [comment]
Ca marche bien là je comprend pas. Je clos.

**Comment by lecault** [comment]
Je pense que GéoBretagne a du buger lorsque tu as testé.
