### ISSUE TITLE
Plugin print : personnalisation de l'image

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#829]
## Environnement

Version mviewer: 3.10-snapshot

## Description

Dans ma configuration, je veux personnaliser le logo comme ceci : 

        "ownerLogo": "https://geobretagne.fr/pub/logo/region-bretagne.jpg",

Le problème est que le logo ne s'affiche pas dans le gabarit : il ajoute un /.

src="https://geobretagne.fr/pub/logo/region-bretagne.jpg/"

## Ce que je devrai voir

Pas de / à la fin de mon URL 

## Screeenshot

![image](https://github.com/mviewer/mviewer/assets/5269430/677d1a69-7dc7-4585-88e8-cf0347fb4e04)

**Comment by Gaetanbrl** [comment]
Fix apporté sur develop
