### ISSUE TITLE
Migration des services IGN vers la géoplateforme

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#834]
**Présentation**

Migration des services IGN utilisés dans le mviewer vers la GéoPlateforme.

En bonus : mises à jour des adresses GéoBretagne vers nos nouveaux services.

**Comment by lecault** [comment]
Exemples de commandes lancées : 

sed -i 's/https:\/\/wxs.ign.fr\/decouverte\/geoportail\/wmts/https:\/\/data.geopf.fr\/wmts/' addlayers.xml
sed -i 's/https:\/\/wxs.ign.fr\/ortho\/geoportail\/r\/wms/https:\/\/data.geopf.fr\/wms-r\/wms/' *.xml
sed -i 's/https:\/\/geoservices.ign.fr\/services-web-decouverte/https:\/\/geoservices.ign.fr\/services-geoplateforme-diffusion/' *.xml
sed -i 's/https:\/\/www.geoportail.gouv.fr\/assets\/images\/logo-geoportail.svg/img\/basemap\/geoservices.png/' *.xml
sed -i 's/https:\/\/www.geoportail.gouv.fr\//https:\/\/geoservices.ign.fr\/services-geoplateforme-diffusion/' *.xml

J'ai remarqué un problème sur le getlegendgraphic.
Exemple : https://data.geopf.fr/wms-v/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&SLD_VERSION=1.1.0&FORMAT=image/png&WIDTH=30&HEIGHT=20&LEGEND_OPTIONS=fontName%3AOpen%20Sans%3BfontAntiAliasing%3Atrue%3BfontColor%3A0x777777%3BfontSize%3A10%3Bdpi%3A96&TRANSPARENT=true&LAYER=BDGEODESIQUE-RN_BDD-POI_WLD&STYLE=

**Comment by lecault** [comment]
J'ai la réponse sur le GetlegendGraphic :  

> Les requêtes GetLegendGraphic ne sont plus supportées sur la version 1.3.0 du WMS Vecteur sur la Géoplateforme.
> 
> Malgré tout, il est encore possible d'effectuer la requête GetLegendGraphic sur la version 1.1.1 : https://data.geopf.fr/wms-v/ows?service=WMS&version=1.1.1&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=BDGEODESIQUE-RN_BDD-POI_WLD
> 

Quelle réponse apporter côté MViewer ?

Une possibilité est de mettre un paramètre legendurl :	legendurl="https://data.geopf.fr/wms-v/ows?service=WMS&amp;version=1.1.1&amp;request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=20&amp;height=20&amp;layer=BDGEODESIQUE-RN_BDD-POI_WLD"

**Comment by lecault** [comment]
Je confirme : 

7.5 GetLegendGraphic (SLD WMS only)
The optional GetLegendGraphic operation applies only to a Styled Layer Descriptor
WMS. See the SLD specification [3] for this operation.

**Comment by Gaetanbrl** [comment]
Donc en gros, il faut modifier le paramètre OWS option de la couche et forcer la version 1.1.0 c'est ca ?

**Comment by lecault** [comment]
Ah je connaissais pas ce paramètre.

Et non ça ne fonctionne pas, il n'applique la version qu'au GetMap (voir extrait doc). Evolution pour élargissement au GetLegendGraphic ?

Extrait doc : 
owsoptions : Pour une couche WMS, permet de forcer certains paramètres des requêtes GetMap. Exemple : « VERSION:1.1.1,EXCEPTIONS:application/vnd.ogc.se_inimage ».

**Comment by Gaetanbrl** [comment]
> Une possibilité est de mettre un paramètre legendurl 

Je pense qu'on ne va pas aller plus loin pour le moment car ce serait une adaptation uniquement pour la geoplateforme.

Issue à fermer @lecault ?
