### ISSUE TITLE
Migration des services IGN SCAN vers la géoplateforme

### ISSUE THREAD

**Issue by frgis** [mviewer/mviewer#839]
## Environnement

Version mviewer: 3.9.1

Navigateur: Microsoft Edge v 120

## Description

Bonjour,

dans le cadre du déploiement de la géoplateforme (IGN) l'accès aux services WMS et WMTS à accès restreint (les SACN(s)) nécessite à priori l'utilisation d'une clé à insérer dans le Header de l'URL (https://geoservices.ign.fr/documentation/services/utilisation-sig/tutoriel-qgis/gpf-wms-wmts-donneesnonlibres).
Je crois que ce n'est pas possible dans Mviewer ?

Merci

**Comment by lecault** [comment]
Non ça n'est pas possible en effet.

J'ai aussi testé l'URL provisoire https://data.geopf.fr/private/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities&apikey=ign_scan_ws

Question : est-ce que le développement d'une option ressemblant à owoption pour les couches WMS peut être une solution ?

**Comment by frgis** [comment]
Bonjour,

merci pour le retour et la confirmation.
Est-ce qu'une adaptation du produit est envisageable d'ici fin Janvier ?
La bascule vers la Géoplateforme intervient mi-Janvier.

SI j'ai bien compris, l'IGN va quand même laisser après mi-Janvier un mécanisme de redirection pour ceux qui n'auraient pas encore basculés, mais conseille vivement de passer aux flux de la Géoplateforme le plus rapidement possible car ce mécanisme de redirection risque d'être saturé s'il est trop sollicité.

De plus, je me demande si le système de redirection fonctionnera avec les ressources sécurisées comme évoqué ici (scans).

D'où ma question pour pouvoir planifier une éventuelle mise à jour de Mviewer en tout début d'année si une évolution est prévue en ce sens.

Merci pour vos retours !
Et bonnes fêtes de fin d'année

**Comment by Gaetanbrl** [comment]
> Question : est-ce que le développement d'une option ressemblant à owoption pour les couches WMS peut être une solution ?

Pour rajouter des infos dans le header @lecault ?

**Comment by lecault** [comment]
> > Question : est-ce que le développement d'une option ressemblant à owoption pour les couches WMS peut être une solution ?
> 
> Pour rajouter des infos dans le header @lecault ?

Ou dans l'URL type apikey=. Le problème est que ce n'est pas trop documenté pour le moment et que le système de clé n'est pas encore prêt. Mais  je pense que c'est la piste à privilégier ?

@frgis on va attendre janvier pour voir si l'IGN documente mieux cette partie là et sinon on se rapprochera d'eux pour voir ce qu'on peut faire.

**Comment by frgis** [comment]
D'accord, merci pour votre réactivité.
Vous voulez que je contacte l'IGN pour demander des informations et leur donner le lien vers ce ticket mviewer ?
Bonne soirée.

**Comment by lecault** [comment]
> D'accord, merci pour votre réactivité. Vous voulez que je contacte l'IGN pour demander des informations et leur donner le lien vers ce ticket mviewer ? Bonne soirée.

Oui avec plaisir

**Comment by frgis** [comment]
Demande envoyée, bonne journée.

**Comment by frgis** [comment]
Bonjour,

pour information, à ce jour l'IGN me renvoi vers cette page : https://geoservices.ign.fr/actualites/2023-11-20-acces-donnesnonlibres-gpf

Cette ressource indique que les deux modes semblent fonctionner, je cite: "L’accès aux données non libres se fait sur la Géoplateforme via des points d’accès privés soumis à un contrôle des accès. Chaque service (à titre d’exemple WMTS) possède un unique point d’accès privé (URL) qui expose les données non libres. Pour y accéder (dans la limite des droits accordés à l'utilisateur), il est nécessaire de disposer d’une clé à déclarer en paramètre ou en en-tête des appels au point d’accès privé."

Les deux méthodes semblent donc possibles.
Ce matin j'ai envoyé un mail à l'IGN pour leur demander laquelle est à privilégier.

Par contre, cela fonctionne pour les flux WMTS en baselayer pour Cartes IGN en mettant la clé en paramètre de l'URL : 
```
<baselayer  type="WMTS" id="Carte_IGN" label="Carte IGN" title="Carte IGN" thumbgallery="apps/chassev2/img/carteign_32.png"
            url="https://data.geopf.fr/private/wmts?apikey=ign_scan_ws" layers="GEOGRAPHICALGRIDSYSTEMS.MAPS"  style="normal" fromcapacity="false" attribution="© IGN 2022 - Copie et reproduction interdite" visible="false" format="image/jpeg" matrixset="PM" />
```

J'aurais pas cru au départ que Mviewer sache gérer la partie après le ? en conservant le paramètre apikey tout en construisant le reste de façon dynamique mais à priori ça fonctionne !

Je reviens vers vous quand j'ai  la réponse de l'IGN.

Bonne journée.

**Comment by lecault** [comment]
J'avais pas fait attention que ça marche. Issue à fermer ?

**Comment by frgis** [comment]
Bonjour, 
je ferme l'issue.
Merci bonne journée.
