### ISSUE TITLE
Index.html - Duplication de div #searchresults 

### ISSUE THREAD

**Issue by Agath21** [mviewer/mviewer#842]
## Environnement

Version mviewer: Develop

## Description

En souhaitant déplacer la barre de recherche, j'ai remarqué que la div `#searchresults` (permettant d'afficher les résultats de recherche) est dupliquée dans le fichier `index.html` : 
(https://github.com/mviewer/mviewer/blob/dadaa6be09d1445dcf964c3273d42977c91dfa9b/index.html#L241)
https://github.com/mviewer/mviewer/blob/dadaa6be09d1445dcf964c3273d42977c91dfa9b/index.html#L362

Est-ce que cela a un intérêt (si oui changer l'id) ou est-ce une erreur d'inattention ? et qu'il faut donc la supprimer ? 

@spelhate @lecault @Gaetanbrl

**Comment by Gaetanbrl** [comment]
En  effet, ca ne semble pas utile d'en avoir 2 vu le code.
A tester en supprimant celui qui est dans la navbar.

A contrôler seulement si on a pas un cas spécifique qui cible la div selon le parent (wrappeer ou navbar).

**Comment by Gaetanbrl** [comment]
@Agath21 on peut clore ?

**Comment by Agath21** [comment]
De mon côté, c'est ok, je n'ai pas constaté de bug depuis.

**Comment by Gaetanbrl** [comment]
Ok je clos. Merci @Agath21
