### ISSUE TITLE
attributefilter avec 2 ''

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#843]
## Environnement

Version mviewer: 3.9.3

## Etapes

Je vais sur ce kartenn : https://kartenn.region-bretagne.fr/kartoviz/?x=-287709&y=6137894&z=9&l=etude_recensement_patrimoinedbl1**operation%20like%20%27%25aucun%25%27&lb=osm1&config=apps/region/patrimoine/rec_patrimoine.xml&mode=d&c_inventaire=

Je choisis l'opération Inventaire de l'urbanisme rennais de l'entre-deux-guerres : quartier de Villeneuve

Rien ne s'affiche, je fais F12 sur la requête et je vois ça : https://ows.region-bretagne.fr/geoserver/interne/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=etude_recensement_patrimoine&STYLES=&CQL_FILTER=operation%20like%20%27%25Inventaire%20de%20l%27%27urbanisme%20rennais%20de%20l%27entre-deux-guerres%20%3A%20quartier%20de%20Villeneuve%25%27&dc=1702568795451&CRS=EPSG%3A3857&WIDTH=2880&HEIGHT=849&BBOX=-727986.2829226153%2C6008103.925971771%2C152568.28292261524%2C6267684.074028229

La première ' est doublée mais pas la seconde.

## Piste

Je crois que ça vient de là : https://github.com/mviewer/mviewer/blob/c4508ceefdaca6de15c0aefdf1fa94f43da022d0/js/mviewer.js#L3195

**Comment by lecault** [comment]
A priori il faut remplacer par replaceAll : https://kartenn.region-bretagne.fr/kartoviz-dev/?config=apps/region/patrimoine/rec_patrimoine.xml#

**Comment by Gaetanbrl** [comment]
Mergée, je clos
