### ISSUE TITLE
Filter/Export : problème avec valeurs séparées par une virgule

### ISSUE THREAD

**Issue by vfabry** [mviewer/mviewer#845]
## Environnement

Version mviewer: 3.9.3.1

Navigateur: Firefox 115.5

## Description

Sur cette carte : https://www.geo2france.fr/mviewer/?config=apps/pacte_linguistique.xml j'ai mis en place le webcomponent filter + export. L'export excel est vide pour public_visé="Séniors" ou "illetrisme" ou "Alphabetisation"
J'ai du mal à tracer les requêtes qui sont passées pour voir où ça coince.

## Ce que je devrai voir

Je devrais avoir une feuille excel avec des enregistrement dedans.

## Etapes

Sur la couche "structure de lutte contre l’illettrisme", je filtre par le champ "public visé".

**Comment by Gaetanbrl** [comment]
après revu du code, le téléchargement utilise des requêtes. Je regarde.

**Comment by vfabry** [comment]
C'est bizarre cet apostrophe qui se trouve avant illetrisme alors qu'elle n'est pas dans la table...
Ca ressemble à ce que @lecault a noté ici : https://github.com/mviewer/mviewer/issues/843 non ?

**Comment by Gaetanbrl** [comment]
Ca y ressemble en effet mais ce n'est pas le même code (issue différente donc).
Ce que je vois c'est surtout que le code concatène le filtre avec des single quote qui ne sont pas bien comprises par le geoserver.

![image](https://github.com/mviewer/mviewer/assets/16317988/cfd98bed-d929-49b1-a335-0459ed37a89c)

La variable newFilter de ma capture fournie la valeur : 

`"publics='Illettrisme'"`

https://www.geo2france.fr/geoserver/hdf_common/ows?SERVICE=WFS&VERSION=1.0.0&REQUEST=GETFEATURE&TYPENAME=structure_illetrisme&outputFormat=application/json&CQL_FILTER=publics=%27Illettrisme%27

En soit c'est exacte, car il Illettrisme est un string et c'est la bonne syntaxe CQL.

Ce que je ne comprend pas c'est pourquoi avec `'Adultes'` ca marche et pas `'Illetrisme'` ?

"publics='Adultes'"
https://www.geo2france.fr/geoserver/hdf_common/ows?SERVICE=WFS&VERSION=1.0.0&REQUEST=GETFEATURE&TYPENAME=structure_illetrisme&outputFormat=application/json&CQL_FILTER=publics=%27Adultes%27

**Comment by Gaetanbrl** [comment]
J'ai compris ! 
En fait vos données sont faites pour fonctionner avec le plugin filtre mais le code réalisé ne permet pas de séparer les valeurs séparées par une virgule dans un champ.

Pour Adulte, on a bien des valeurs seule avec la valeur  "public":"Adultes" :

![image](https://github.com/mviewer/mviewer/assets/16317988/2add9e73-bc61-4289-b809-8041172c9789)


Mais Illettrisme n'est jamais seul : 

![image](https://github.com/mviewer/mviewer/assets/16317988/d831443c-b51c-4fdf-81b3-2e54ebebf497)


Donc ca fonctionne quand on utilise le filtre. Mais le téléchargement se contente de faire un filtre CQL avec l'opérateur = et non un LIKE. Le geoserver fonctionne bien, il ne retourne donc aucun résultat car en effet, "Illettrisme" seule n'existe pas.

Cette requête fonctionnerai mieux ainsi avec un LIKE donc :

https://www.geo2france.fr/geoserver/hdf_common/ows?SERVICE=WFS&VERSION=1.0.0&REQUEST=GETFEATURE&TYPENAME=structure_illetrisme&outputFormat=application/json&CQL_FILTER=publics%20LIKE%20%27%25Ille%25%27

**Comment by vfabry** [comment]
une solution serait de séparer par un autre caractère que la virgule ? un '/' par exemple ?

**Comment by Gaetanbrl** [comment]
> une solution serait de séparer par un autre caractère que la virgule ? un '/' par exemple ?

Non il faut corriger le code qui a été fait. En l'état le code marche bien avec le plugin, mais il n'a pas du être testé avec les filtres CQL qui contiennent plusieurs valeurs lors de la réalisation de la fonction de téléchargement. Avec des valeurs simples / uniques ca télécharge bien.

**Comment by vfabry** [comment]
OK, merci @Gaetanbrl je vais voir avec @dds2010  s'il peut corriger ce code

**Comment by Gaetanbrl** [comment]
Sinon on peut voir pour le traiter, ca ne doit pas être une grosse modification

**Comment by Gaetanbrl** [comment]
je peux voir pour le corriger

**Comment by Gaetanbrl** [comment]
Testé / validé par @vfabry . Je clos.
