### ISSUE TITLE
mviewer print : getOptions fails

### ISSUE THREAD

**Issue by fphg** [mviewer/mviewer#859]
## Environnement

Version mviewer:master

## Description

Sur mon instance locale, l'addon print échoue

https://github.com/mviewer/mviewer/blob/master/demo/addons/print/js/components/Block.js ligne 121

```
const mviewerId = configuration.getConfiguration().application.id;
const options = mviewer.customComponents.print.config.options;
return options.mviewer[mviewerId];
```

à remplacer par 

```
const mviewerId = configuration.getConfiguration().application.id;
const options = mviewer.customComponents.print.config.options;
return options[mviewerId].print;
```

**Comment by Gaetanbrl** [comment]
Hello,
Peux-tu copier / coller ici ton fichier config.json utilisé pour le module print stp @fphg ?

**Comment by Gaetanbrl** [comment]
Par défaut ce fichier est dans `demo/addons/print/config.json`

**Comment by fphg** [comment]
hi

j'ai cherché dans le code car un clone mviewer frais ne fonctionne pas (avec un config.xml qui n'est pas frais)

je constatais que standard.json addons/print/layouts/standard.json n'est pas chargé

j'ai trouvé comment faire, avec la structure config.json suivante
options > mviewer > mviewerid > printLayouts

et le code d'origine

... ça fonctionne mais c'est compliqué à comprendre !

car on peut être tenté de remplacer "mviewer" par "mviewerid" comme je l'ai fait

**Comment by Gaetanbrl** [comment]
> ... ça fonctionne mais c'est compliqué à comprendre !

Désolé, on a fait une petite doc dans le README en pensant que ca aller être plus simple à comprendre mais ca n'aide peut être pas vraiment comme on le pensait :

https://github.com/mviewer/mviewer/tree/master/demo/addons/print#installation


> In options (create this key if not available), insert options.mviewer.applicationid (change applicationid by application id value) >like :
>"options": {
>  "mviewer": {
>    "my_print_app": {

**Comment by fphg** [comment]
c'est parce que j'ai pensé autrement - pour ne pas dépendre de demo (qui n'a rien à faire dans une install de prod) j'associe les addons à chaque mviewer

ceci dit ce serait mieux de remplacer my_print_app par my_mviewer_id sinon on confond l'id de l'addon print avec l'id du mviewer

**Comment by Gaetanbrl** [comment]
> pour ne pas dépendre de demo (qui n'a rien à faire dans une install de prod)

+1 👍

**Comment by lecault** [comment]
ton issue me fait penser qu'on n'a pas complété la doc ici https://mviewerdoc.readthedocs.io/fr/stable/doc_tech/config_extensions.html

**Comment by lecault** [comment]
Issue a fermer ?
