### ISSUE TITLE
Doc - Problème recherche & évolution

### ISSUE THREAD

**Issue by Gaetanbrl** [mviewer/mviewer#867]
# Description

Lorsque je recherche un mot clé dans la documentation, la recherche est très longue ou ne retourne pas de résultat.

# Evolution possible

La documentation mviewer est réalisée / buildée avec Sphinx.

Je me demande si on ne pourrait pas envisager d'utiliser le même système que georchestra avec mkdoc-material mais avec des couleurs différentes  :

https://docs.georchestra.org/cadastrapp/latest/guides_techniques/administrer/donnees_dgfip/
https://squidfunk.github.io/mkdocs-material/

De mémoire la migration n'est pas forcément complexe (à vérifier), l'administration plus simple et le style plus sympa.

On pourrait alors passer par une github page pour la documentation (dépôt séparé ?).

Qu'en pensez-vous ?

**Comment by lecault** [comment]
Bon je crois que j'ai trouvé. En changeant la version dans requirement. exemple ici : https://mviewerdoc.readthedocs.io/fr/issue-867/search.html?q=fuse&check_keywords=yes&area=default

Bon je vais remettre tout ça au propre

**Comment by Gaetanbrl** [comment]
Merci @loic

**Comment by lecault** [comment]
Du coup je clos l'issue. La recherche est débugée : https://mviewerdoc.readthedocs.io/fr/latest/

Par contre, effectivement la question de changer le support de la doc peut être posée.
