### ISSUE TITLE
[ Plugin TrackView ] Custom component pour la visualisation de parcours GPX

### ISSUE THREAD

**Issue by pierrejego** [mviewer/mviewer#885]
**Présentation**

Avoir une extension dans mviewer qui permet d'afficher des parcours pour des évènements sportif ( sens, altimétrie, distance )

**Description fonctionnelle**

L'idée ici est de créer une extension permettant d'utiliser dans mviewer les données issues d'un fichier GPX et d'en afficher différentes information : 
- Sens du parcours
- Point tous les kilomètres
- Altimétrie dans un graphique lié au parcours.

Une application existante qui pourrait ressembler à la cible : 
https://app.racedaymap.com/otillo-swimrun-cannes/experience

**Description technique**

Utilisation des librairies existantes de Mviewer, si possible intégration du GPX sans prétraitement
En prérequis il faut que le GPX contiennent des données suffisamment précises et "propres" 

Ce développement fait partie d'une stage ou le projet sera suivi ici : https://github.com/orgs/jdev-org/projects/8

**Comment by darbonc** [comment]
Belle idée !!

Pour rendre cette extension plus "généraliste", une option  permettant l'affichage des POI pourrait peut-être être pertinente ? Cela permettrait par exemple de placer des "points de vue" le long d'un parcours de randonnées, des "points de passages" pour les courses d'orientation, etc.

Le format  gpx : https://www.topografix.com/gpx.asp
