### ISSUE TITLE
Légende de couche et échelle de visualisation

### ISSUE THREAD

**Issue by LaurentTesson** [mviewer/mviewer#890]
Bonjour, Si on utilise 'scalemax' dans une balise <layer> alors la légende de la couche disparait dans la visualisation du MViewer quel que soit le niveau de zoom. Seul le symbole 'invisible' apparait sous le nom de la couche.
Il ne me semble pas que cela se produisait auparavant.

**Comment by Gaetanbrl** [comment]
Salut @LaurentTesson,
As-tu un lien vers un mviewer d'exemple qui permet de reproduire ce comportement ?
Merci :)

**Comment by lecault** [comment]
Salut. Je crois qu'il faut scalemin aussi

**Comment by LaurentTesson** [comment]
Bonjour,

Merci et Bravo Loïc,
C'est bien cela : il faut les 2 instructions en même temps (scalemax et scalemin) même si une seule est utile ! Info à noter dans mviewerdoc.readthedocs.
Merci et bonne fin de journée
Laurent Tesson
________________________________
De : Loïc E ***@***.***>
Envoyé : mardi 21 mai 2024 09:44
À : mviewer/mviewer ***@***.***>
Cc : Laurent Tesson ***@***.***>; Mention ***@***.***>
Objet : Re: [mviewer/mviewer] Légende de couche et échelle de visualisation (Issue #890)


Salut. Je crois qu'il faut scalemin aussi
