### ISSUE TITLE
Ajout de couche : correction et ajout de nouveaux serveurs

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#915]
**Description**

Dans le plugin ajout de couche https://kartenn.region-bretagne.fr/kartoviz/?config=demo/addlayers.xml, certains services ne fonctionnent plus.

Par ailleurs, il serait intéressant de pouvoir sortir du cœur du mviewer ce paramétrage pour le personnaliser.

**Comment by Gaetanbrl** [comment]
> certains services ne fonctionnent plus.

Quelle est la raison ?

**Comment by lecault** [comment]
WMS : 
- j'ai du modifier les urls pour haut de france et IGN (geoplateforme)
- Pour geoide j'ai une erreur CORS mais pas sur que ce soit ça => je vais l'enlever

CSW : 
- PIGMA et Geo2France fonctionne
- Grand Lyon erreur CORS
- GéoBretagne : problème de filtre sur le protocole

**Comment by lecault** [comment]
Exemple :

- Geo2France : renvoie toutes les métadonnées https://www.geo2france.fr/geonetwork/srv/fre/csw?request=GetRecords&service=CSW&version=2.0.2&typeNames=csw:Record&resultType=results&maxRecords=100&startPosition=1&ELEMENTSETNAME=full&constraintLanguage=CQL_TEXT&CONSTRAINT_LANGUAGE_VERSION=1.1.0&CONSTRAINT=linkProtocol%3D%27OGC%3AWMS%27
- GeoBretagne : renvoie aucune métadonnée https://geobretagne.fr/geonetwork/srv/fre/csw?request=GetRecords&service=CSW&version=2.0.2&typeNames=csw:Record&resultType=results&maxRecords=100&startPosition=1&ELEMENTSETNAME=full&constraintLanguage=CQL_TEXT&CONSTRAINT_LANGUAGE_VERSION=1.1.0&CONSTRAINT=linkProtocol%3D%27OGC%3AWMS%27

**Comment by lecault** [comment]
Intégration des corrections dans develop.

Pour le souci de GéoBretagne, ça marche avec le code suivant : 

    {"label":"Catalogue GeoBretagne","url":"https://geobretagne.fr/geonetwork/srv/fre/csw","defaultfilter":"linkProtocol like '%WMS'"},
