### ISSUE TITLE
Carte centrée sur une adresse à l'ouverture

### ISSUE THREAD

**Issue by spelhate** [mviewer/mviewer#925]
**Présentation**

Carte centrées sur une adresse à l'ouverture

**Description fonctionnelle**

J'ai besoin de produire en série des cartes mviewer centrées sur une adresse

**Description technique**

Je propose d'ajouter deux nouveaux paramètres d'URL  **q** & **qtype** afin de pouvoir centrer une carte mviewer sur une adresse avec mise en évidence de l'adresse à l'ouverture de l'application.
Exemple d'appel:
 `mviewer?q=71rue dupont des loges rennes&qtype=ban`
La fonctionnalité récupérerait alors la question (q) et utiliserait le service de la BAN pour récupérer les coordonnées X et Y afin de permettre un centrage sur ces coordonnées.

J'hésite à partir sur un plugin ou à intégrer ça dans le cœur. Qu'en pensez vous ?

**Comment by Gaetanbrl** [comment]
> J'hésite à partir sur un plugin ou à intégrer ça dans le cœur. Qu'en pensez vous ?

Ca mérite d'être dans le coeur :)

**Comment by Gaetanbrl** [comment]
> mviewer?q=71rue dupont des loges rennes&qtype=ban

Le nom de paramètre `q` c'est pour rester iso avec la ban qui utilise le même nom ? Si les utilisateurs veulent un paramètre évocateur, ce nom n'est pas parlant (perso `q` ca me va).

**Comment by Gaetanbrl** [comment]
En y pensant, ce serait pas mal de prévoir un parsing de l'URL pour rechercher des paramètres supplémentaires selon le qtype (les paramètres seront attendus et listés dans le code mviewer).

Je pense notamment au moins aux paramètres qui permettent d'augmenter la précision (souvent attendu).

Par exemple :

* Pour la BAN : 
> lat / lon / type / postcode / citycode

https://adresse.data.gouv.fr/api-doc/adresse

* Pour Nominatim
> amenity / street / city / county / state / country / postalcode

https://nominatim.org/release-docs/develop/api/Search/

**Comment by spelhate** [comment]
> Le nom de paramètre `q` c'est pour rester iso avec la ban qui utilise le même nom ? Si les utilisateurs veulent un paramètre évocateur, ce nom n'est pas parlant (perso `q` ca me va).

Oui mais on pourrait mettre **query**  à la place.
J'ai dans l'idée d'étendre cette première implémentation pour faire des recherches (q=....) en sollicitant différents services (**ban** pour le moment mais **cadastre** plus tard pour pouvoir se localiser sur une parcelle)

**Comment by Gaetanbrl** [comment]
Ban c'est déjà bien pour les services localisés en France.
Cadastre = un backend cadastrapp ?

**Comment by spelhate** [comment]
> Ban c'est déjà bien pour les services localisés en France. Cadastre => un backend cadastrapp ?

Pourquoi pas si ne nécessite pas d'être authentifié. A voir

**Comment by Gaetanbrl** [comment]
> si ne nécessite pas d'être authentifié

Il y a un niveau CNIL qui permet l'accès aux données "non privée".
Le CRAIG permet par exemple la consultation des parcelles sans être authent : 

https://ids.craig.fr/mapstore/#/context/cadastre

https://ids.craig.fr/cadastrapp/services/getParcelle?parcelle=6303340000C1179

**Comment by spelhate** [comment]
Je propose de rendre ce service paramétrable via la conf xml + étendre ce service à d'autres besoins de localisation ex (parcelles cadastrales)
Ce qui pourrait donner au niveau conf xml

```xml
<urlparams>
     <qtype name="ban" url="https://api-adresse.data.gouv.fr/search/" />
     <qtype name="cadastre" url="https://apicarto.ign.fr/api/cadastre/parcelle" />
</urlparams>
```

Et ensuite pour les URL de localisation à l'adresse : 

- `?q=71 rue dupont des loges rennes&qtype=ban`

Et pour les URL de localisation à la parcelle, on aurait :

- `?q=code_insee%3D35238%26section%3DAB%26numero%3D0001&qtype=cadastre`
