### ISSUE TITLE
[Régression] Outil de mesure ne renvoit plus la mesure

### ISSUE THREAD

**Issue by lecault** [mviewer/mviewer#931]
## Environnement

Version mviewer: 3.12

## Description

L'outil de mesure fonctionne mal. Le tracé apparaît à l'écran mais on ne voit plus la mesure.

## Etapes

- https://kartenn.region-bretagne.fr/vn/
- Activer l'outil de mesure
- Faire un tracé linéaire ou polygone

![image](https://github.com/user-attachments/assets/2508531a-2ce6-478e-a8b6-bf024fca8568)

Je pense que cela vient de l'outil draw

**Comment by lecault** [comment]
Confirmation sur un essai sur la branche de la PR #914 :  https://kartenn.region-bretagne.fr/kartoviz-jdev/?config=apps/region/vn/vn_els7.xml#

**Comment by Gaetanbrl** [comment]
Pas cool, à corriger du coup rapidement.
